// import axios from "axios";
// import { AuthenticatedTemplate } from "@azure/msal-react";
// import { useEffect, useState } from "react";
// import { config } from "../config";
// import Select from "react-select";
// import "../styles/EmailTemplate.css";
// import Loader from "react-js-loader";
// import { toast } from "react-toastify";
// import { CKEditor } from "@ckeditor/ckeditor5-react";
// import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
// import { useLocation, useNavigate } from "react-router-dom";
// import { BiChevronLeft } from "react-icons/bi";
// import { accessLogApi } from "../utils/AccessLogApi";
// export const EmailTemplate = () => {
//   const loader = (
//     <Loader
//       type="spinner-circle"
//       bgColor={"#000000"}
//       title={"bubble-scale"}
//       color={"#FFFFFF"}
//       size={50}
//     />
//   );
//   const { state } = useLocation();
//   const navigate = useNavigate();
//   const [submitLoader, setSubmitLoader] = useState(false);
//   const [TemplateOptions, setTemplateOptions] = useState([]);
//   const [EmailData, setEmailData] = useState({
//     subject: "",
//     TempletName: "",
//     useCaseTemplate: "",
//   });
//   const [recipient, setRecipient] = useState([]);
//   const [recipientInput, setRecipientInput] = useState("");
//   const [recipientError, setRecipientError] = useState(null);
//   const [EditorData, setEditorData] = useState(
//     `<html><head><style>table, th, td {{border: 1px solid black;border-collapse: collapse}}</style></head><body><b>Description</b>:<br>Following information generated by automated system.<br><b>{fan_name} - Fan Efficiency gone down by {critical_percent:.1f}% at {current_time}</b><br>Critical parameters listed below with its instantaneous value when the exception has been raised<br><br><br><table><tr><th>Parameters</th><th>Values</th></tr><tr><td><FONT COLOR="RED">Fan Efficiency</td><td><FONT COLOR="RED">{current_efficiency:.3f}%</td></tr><tr><td>Fan Speed</td><td>{current_speed:.2f} RPM</td></tr><tr><td>Fan load</td><td>{current_load:.2f} KW</td></tr><tr><td>Fan Inlet Draft</td><td>{current_inlet:.2f}</td></tr><tr><td>Fan Outlet Draft </td><td>{current_outlet:.2f}</td></tr><tr><td>Fan Temperature</td><td>{current_temp:.2f}℃</td></tr></body></html>`
//   );

//   const setTemplateData = () => {
//     let EditData = state?.rowdata;
//     if (state?.copyData) {
//       EditData = state?.copyData;
//       EditData.EmailTemplateName = EditData.EmailTemplateName + "- Copy";
//     }
//     let Temp = { ...EmailData };

//     Temp.TempletName = EditData.EmailTemplateName;
//     Temp.subject = EditData.Subject;
//     Temp.useCaseTemplate = EditData.UseCaseTemplate;

//     setRecipient(EditData.Recipients);
//     EditData.Description = EditData.Description.replaceAll("@@@", ",");

//     setEditorData(EditData.Description.split("</style>").pop());

//     setEmailData(Temp);
//     state.EditFlag = false;
//   };

//   useEffect(() => {
//     accessLogCBM()
//     if (
//       state?.rowdata === undefined &&
//       window.location.href.split("/").pop() === "editEmailTemplate"
//     ) {
//       navigate("/EmailTemplateList");
//     }
//     if (
//       TemplateOptions.length > 0 &&
//       (state?.rowdata || state?.copyData) &&
//       state.EditFlag
//     ) {
//       // console.log("here2222222");
//       setTemplateData();
//     }
//   }, [TemplateOptions]);

//   const accessLogCBM = () => {
//     let payload = {
//       userId: JSON.parse(sessionStorage.getItem("accountDetails"))?.username,
//       ip: "",
//       module: "CBM",
//       plant: "-",
//       url: window.location.href,
//       options: "",
//       plant_or_section: "CBM",
//     };
//     accessLogApi(payload)
//   }

//   const getTemplateData = () => {
//     let payload = {
//       userid: JSON.parse(sessionStorage.getItem("accountDetails"))?.username,
//     };
//     axios.post(config.BaseUrl + "/cbm/template/getTemplateData", payload, {
//       headers: {
//         Authorization: `Bearer ${JSON.parse(localStorage.getItem("login"))?.token
//           }`,
//       },
//     })
//       .then((res) => {
//         res = res.data.result;
//         if (res === "No Records Found") {
//           setTemplateOptions([]);
//         } else {
//           let TempList = {};
//           res.map((val) => {
//             TempList[val.TemplateName + val.Timestamp] = {
//               value: val.TemplateName,
//               label: val.TemplateName + " UseCase : " + val.UseCase,
//               Timestamp: val.Timestamp,
//             };
//           });
//           TempList = Object.values(TempList);

//           setTemplateOptions(TempList);
//         }
//       })
//       .catch((err) => {
//         toast.error(err.message);
//       });
//   };
//   const handleChangeRecipientInput = (event) => {
//     setRecipientInput(event.target.value);
//     setRecipientError("");
//   };
//   const handleDeleteEmail = (item) => {
//     let tempRecipient = [...recipient];
//     tempRecipient = tempRecipient.filter((i) => i !== item);
//     setRecipient(tempRecipient);
//   };
//   const handleKeyDownRecipient = (event) => {
//     if (["Enter", "Tab", ","].includes(event.key)) {
//       event.preventDefault();

//       var value = recipientInput.trim();
//       if (!/[\w\d\.-]+@[\w\d\.-]+\.[\w\d\.-]+/.test(value)) {
//         setRecipientError("Invalid Email");
//       } else {
//         if (recipient.includes(value)) {
//           setRecipientError("Already in List");
//         } else {
//           let trec = [...recipient];
//           trec.push(value);
//           setRecipient(trec);
//           setRecipientInput("");
//         }
//       }
//     }
//     // setRecipientInput(event.target.value);
//   };

//   const handleInput = (e) => {
//     let tempEmaildata = { ...EmailData };
//     tempEmaildata[e.target.name] = e.target.value;
//     setEmailData(tempEmaildata);
//   };
//   const handleChangeSelect = (e) => {
//     let tempEmaildata = { ...EmailData };
//     tempEmaildata.useCaseTemplate = e.value;
//     tempEmaildata.TempletName = e.value;
//     tempEmaildata.subject = e.value;
//     setEmailData(tempEmaildata);

//   };
//   useEffect(() => {
//     getTemplateData();
//   }, []);

//   const SendData = () => {
//     if (EmailData.useCaseTemplate === "") {
//       toast.error("Please Select UseCase Template");
//       return;
//     }
//     if (EmailData.subject === "") {
//       toast.error("Please Enter Subject");
//       return;
//     }
//     if (recipient.length === 0) {
//       toast.error("Please Enter recipient");
//       return;
//     }

//     let postUrl = config.BaseUrl + "/cbm/template/sendEmailTemplateData";
//     let payload = {
//       userid: JSON.parse(sessionStorage.getItem("accountDetails"))?.username,
//       EmailTemplateName: EmailData.TempletName,
//       Subject: EmailData.subject,
//       UseCaseTemplate: EmailData.useCaseTemplate,
//       Recipients: recipient,
//       Description: ` <style>table, th, td {{border: 1px solid black;border-collapse: collapse}}</style>${EditorData}`,
//     };

//     if (state?.rowdata) {
//       postUrl = config.BaseUrl + "/cbm/template/editEmailTemplateData";
//       payload.TimeStamp = state.rowdata.Timestamp;
//     }
//     setSubmitLoader(true);
//     axios
//       .post(postUrl, payload, {
//         headers: {
//           Authorization: `Bearer ${JSON.parse(localStorage.getItem("login"))?.token
//             }`,
//         },
//       })
//       .then((res) => {
//         res = res.data.result;

//         if (state?.rowdata) {
//           toast.success("Template Updated Successfully.");
//         } else {
//           toast.success("Template Added Successfully.");
//         }
//         setSubmitLoader(false);
//         navigate("/EmailTemplateList");
//       })
//       .catch((err) => {
//         toast.error(err.message);
//         setSubmitLoader(false);
//       });
//   };
//   return (
//     <AuthenticatedTemplate>
//       <div className="dash-top pb-2">
//         <div className="mycard mt-2">
//           <div className="back">
//             <BiChevronLeft
//               size={25}
//               onClick={() => {
//                 navigate("/EmailTemplateList");
//               }}
//             />
//             {/* <span>Back </span>  */}
//           </div>
//           <div className="row mt-3">
//             <div className="col-6 multiTagSelection">
//               <label className="mb-2">
//                 Select UseCase Template <span className="text-danger">*</span>
//               </label>

//               {
//                 <Select
//                   value={
//                     EmailData.useCaseTemplate !== "" && TemplateOptions.filter((item) => item.value === EmailData.useCaseTemplate)
//                   }
//                   placeholder="Select Template"
//                   name="Template"
//                   onChange={(e) => handleChangeSelect(e)}
//                   options={TemplateOptions}
//                   isDisabled={
//                     window.location.href.split("/").pop() ===
//                     "editEmailTemplate"
//                   }
//                   className="basic-multi-select"
//                   classNamePrefix="select"
//                 />
//               }
//               <div className="colcustom-2 pl-2 pr-2 cutomremoveindi">
//                 {EmailData.useCaseTemplate !== "" && !!!state?.rowdata && (
//                   <button
//                     onClick={() => {
//                       let temp = { ...EmailData };
//                       temp.useCaseTemplate = "";
//                       setEmailData(temp);
//                     }}
//                     className="p-2 btn btnfrst"
//                   >
//                     X
//                   </button>
//                 )}
//               </div>
//             </div>
//             <div className="col-6 multiTagSelection">
//               <label className="mb-2">
//                 Email Template Name <span className="text-danger">*</span>
//               </label>
//               <input
//                 name="TempletName"
//                 placeholder="Enter Template Name"
//                 onChange={(e) => handleInput(e)}
//                 value={EmailData.TempletName}
//                 style={{ minWidth: "100% " }}
//                 disabled={!state?.copyData
//                   // window.location.href.split("/").pop() === "editEmailTemplate"
//                 }
//                 className="form-control"
//               />
//             </div>

//           </div>

//           <div className="row mt-3">
//             <div className="col-6">
//               <label className="mb-2">
//                 Mail Subject <span className="text-danger">*</span>
//               </label>
//               <input
//                 name="subject"
//                 placeholder="Enter Subject"
//                 onChange={(e) => handleInput(e)}
//                 value={EmailData.subject}
//                 className="form-control"
//               />
//             </div>
//             <div className="col-6">
//               <label className="mb-2">
//                 Recipients <span className="text-danger">*</span> :
//               </label>
//               {recipient.map((item) => (
//                 <div className="tag-item" key={item}>
//                   {item}
//                   <button
//                     type="button"
//                     className="button"
//                     onClick={() => handleDeleteEmail(item)}
//                   >
//                     &times;
//                   </button>
//                 </div>
//               ))}
//               <input
//                 className={
//                   "form-control " +
//                   (recipientError !== "" && recipientInput !== ""
//                     ? "error"
//                     : "")
//                 }
//                 value={recipientInput}
//                 placeholder="Type email addresses and press `Enter`"
//                 onKeyDown={(e) => handleKeyDownRecipient(e)}
//                 onChange={(e) => handleChangeRecipientInput(e)}
//               // onPaste={(e) => handlePasteRecipient()}
//               />
//               {recipientError !== "" && recipientInput !== "" && (
//                 <span className="text-danger"> {recipientError}</span>
//               )}
//             </div>
//           </div>
//           <div className="mt-3">
//             <b>Note : </b>
//             <label>
//               Avaliable Dynamic Parameters are as below Please include them with
//               curley Brackets like for Example {"{"}critical_limit{"}"}
//             </label>

//             <div className="row mt-3">
//               <div className="col-2">Parameter Names : </div>
//               <div className="col-10">
//                 <div className="tag-item">plant_name</div>
//                 <div className="tag-item">fan_name</div>
//                 <div className="tag-item"> critical_limit</div>
//                 <div className="tag-item"> timestamp</div>
//                 <div className="tag-item"> current_efficiency</div>
//                 <div className="tag-item">current_speed</div>
//                 <div className="tag-item"> current_load</div>
//                 <div className="tag-item"> current_inlet</div>
//                 <div className="tag-item"> current_outlet</div>
//                 <div className="tag-item">current_temp</div>
//                 <div className="tag-item">critical_percent</div>
//               </div>
//             </div>
//           </div>
//           <div className="editorContainer mt-3">
//             <label className="mb-2">
//               <b>Template Body</b>
//             </label>
//             <CKEditor

//               editor={ClassicEditor}
//               data={EditorData}
//               onChange={(event, editor) => {
//                 const data = editor.getData();
//                 setEditorData(data);
//               }}
//             />
//             <div className="mt-3 text-right">
//               {submitLoader && loader}
//               <button
//                 className="btn btnfrst mr-1"
//                 disabled={EmailData.TempletName === "" || submitLoader}
//                 onClick={() => SendData()}
//               >
//                 {state?.rowdata ? "Update" : "Submit"}
//               </button>
//             </div>
//           </div>
//         </div>
//       </div>
//     </AuthenticatedTemplate>
//   );
// };



import axios from "axios";
import { AuthenticatedTemplate } from "@azure/msal-react";
import { useEffect, useState } from "react";
import { config } from "../config";
import Select from "react-select";
import "../styles/EmailTemplate.css";
import Loader from "react-js-loader";
import { toast } from "react-toastify";
import { CKEditor } from "@ckeditor/ckeditor5-react";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import { useLocation, useNavigate } from "react-router-dom";
import { BiChevronLeft } from "react-icons/bi";
import { accessLogApi } from "../utils/AccessLogApi";
import { ScreenLoader } from "./Loader/Loader";
export const EmailTemplate = () => {
  const loader = (
    // <Loader
    //   type="spinner-circle"
    //   bgColor={"#000000"}
    //   title={"bubble-scale"}
    //   color={"#FFFFFF"}
    //   size={50}
    // />
    <ScreenLoader />
  );
  const { state } = useLocation();
  const navigate = useNavigate();
  const [submitLoader, setSubmitLoader] = useState(false);
  const [TemplateOptions, setTemplateOptions] = useState([]);
  const [EmailData, setEmailData] = useState({
    subject: "",
    TempletName: "",
    useCaseTemplate: "",
  });
  const [recipient, setRecipient] = useState([]);
  const [recipientInput, setRecipientInput] = useState("");
  const [recipientError, setRecipientError] = useState(null);
  const [EditorData, setEditorData] = useState(
    `<html><head><style>table, th, td {{border: 1px solid black;border-collapse: collapse}}</style></head><body><b>Description</b>:<br>Following information generated by automated system.<br><b>{fan_name} - Fan Efficiency gone down by {critical_percent:.1f}% at {current_time}</b><br>Critical parameters listed below with its instantaneous value when the exception has been raised<br><br><br><table><tr><th>Parameters</th><th>Values</th></tr><tr><td><FONT COLOR="RED">Fan Efficiency</td><td><FONT COLOR="RED">{current_efficiency:.3f}%</td></tr><tr><td>Fan Speed</td><td>{current_speed:.2f} RPM</td></tr><tr><td>Fan load</td><td>{current_load:.2f} KW</td></tr><tr><td>Fan Inlet Draft</td><td>{current_inlet:.2f}</td></tr><tr><td>Fan Outlet Draft </td><td>{current_outlet:.2f}</td></tr><tr><td>Fan Temperature</td><td>{current_temp:.2f}℃</td></tr></body></html>`
  );

  const setTemplateData = () => {
    let EditData = state?.rowdata;
    if (state?.copyData) {
      EditData = state?.copyData;
      EditData.EmailTemplateName = EditData.EmailTemplateName + "- Copy";
    }
    let Temp = { ...EmailData };

    Temp.TempletName = EditData.EmailTemplateName;
    Temp.subject = EditData.Subject;
    Temp.useCaseTemplate = EditData.UseCaseTemplate;

    setRecipient(EditData.Recipients);
    EditData.Description = EditData.Description.replaceAll("@@@", ",");

    setEditorData(EditData.Description.split("</style>").pop());

    setEmailData(Temp);
    state.EditFlag = false;
  };

  useEffect(() => {
    accessLogCBM()
    if (
      state?.rowdata === undefined &&
      window.location.href.split("/").pop() === "editEmailTemplate"
    ) {
      navigate("/EmailTemplateList");
    }
    if (
      TemplateOptions.length > 0 &&
      (state?.rowdata || state?.copyData) &&
      state.EditFlag
    ) {
      // console.log("here2222222");
      setTemplateData();
    }
  }, [TemplateOptions]);

  const accessLogCBM = () => {
    let payload = {
      userId: JSON.parse(sessionStorage.getItem("accountDetails"))?.username,
      ip: "",
      module: "CBM",
      plant: "-",
      url: window.location.href,
      options: "",
      plant_or_section: "CBM",
    };
    accessLogApi(payload)
  }

  const getTemplateData = () => {
    let payload = {
      userid: JSON.parse(sessionStorage.getItem("accountDetails"))?.username,
    };
    axios.post(config.BaseUrl + "/cbm/template/getTemplateData", payload, {
      headers: {
        Authorization: `Bearer ${JSON.parse(localStorage.getItem("login"))?.token
          }`,
      },
    })
      .then((res) => {
        res = res.data.result;
        if (res === "No Records Found") {
          setTemplateOptions([]);
        } else {
          let TempList = {};
          res.map((val) => {
            TempList[val.TemplateName + val.Timestamp] = {
              value: val.TemplateName,
              label: val.TemplateName + " UseCase : " + val.UseCase,
              Timestamp: val.Timestamp,
            };
          });
          TempList = Object.values(TempList);

          setTemplateOptions(TempList);
        }
      })
      .catch((err) => {
        toast.error(err.message);
      });
  };
  const handleChangeRecipientInput = (event) => {
    setRecipientInput(event.target.value);
    setRecipientError("");
  };
  const handleDeleteEmail = (item) => {
    let tempRecipient = [...recipient];
    tempRecipient = tempRecipient.filter((i) => i !== item);
    setRecipient(tempRecipient);
  };
  const handleKeyDownRecipient = (event) => {
    if (["Enter", "Tab", ","].includes(event.key)) {
      event.preventDefault();

      var value = recipientInput.trim();
      if (!/[\w\d\.-]+@[\w\d\.-]+\.[\w\d\.-]+/.test(value)) {
        setRecipientError("Invalid Email");
      } else {
        if (recipient.includes(value)) {
          setRecipientError("Already in List");
        } else {
          let trec = [...recipient];
          trec.push(value);
          setRecipient(trec);
          setRecipientInput("");
        }
      }
    }
    // setRecipientInput(event.target.value);
  };

  const handleInput = (e) => {
    let tempEmaildata = { ...EmailData };
    tempEmaildata[e.target.name] = e.target.value;
    setEmailData(tempEmaildata);
  };
  const handleChangeSelect = (e) => {
    let tempEmaildata = { ...EmailData };
    tempEmaildata.useCaseTemplate = e.value;
    tempEmaildata.TempletName = e.value;
    tempEmaildata.subject = e.value;
    setEmailData(tempEmaildata);

  };
  useEffect(() => {
    getTemplateData();
  }, []);

  const SendData = () => {
    if (EmailData.useCaseTemplate === "") {
      toast.error("Please Select UseCase Template");
      return;
    }
    if (EmailData.subject === "") {
      toast.error("Please Enter Subject");
      return;
    }
    if (recipient.length === 0) {
      toast.error("Please Enter recipient");
      return;
    }

    let postUrl = config.BaseUrl + "/cbm/template/sendEmailTemplateData";
    let payload = {
      userid: JSON.parse(sessionStorage.getItem("accountDetails"))?.username,
      EmailTemplateName: EmailData.TempletName,
      Subject: EmailData.subject,
      UseCaseTemplate: EmailData.useCaseTemplate,
      Recipients: recipient,
      Description: ` <style>table, th, td {{border: 1px solid black;border-collapse: collapse}}</style>${EditorData}`,
    };

    if (state?.rowdata) {
      postUrl = config.BaseUrl + "/cbm/template/editEmailTemplateData";
      payload.TimeStamp = state.rowdata.Timestamp;
    }
    setSubmitLoader(true);
    axios
      .post(postUrl, payload, {
        headers: {
          Authorization: `Bearer ${JSON.parse(localStorage.getItem("login"))?.token
            }`,
        },
      })
      .then((res) => {
        res = res.data.result;

        if (state?.rowdata) {
          toast.success("Template Updated Successfully.");
        } else {
          toast.success("Template Added Successfully.");
        }
        setSubmitLoader(false);
        navigate("/EmailTemplateList");
      })
      .catch((err) => {
        toast.error(err.message);
        setSubmitLoader(false);
      });
  };
  return (
    <AuthenticatedTemplate>
      <div className="w-full h-full">

        {/* HEADER */}
        <div className="flex justify-between items-center mb-2 -mt-2">
          <h2 className="flex text-[18px] font-medium font-poppins text-[var(--title)] -mt-2 -ml-0.5">
            Email Template
          </h2>
          <button
            onClick={() => navigate("/EmailTemplateList")}
            className="px-2 py-1
            text-[14px]
            rounded-lg
           !border !border-[var(--button-border)]
            bg-[var(--button-bg)]
            hover:bg-[var(--button-hover-bg)]
            text-[var(--text-color)] font-medium
            transition-all focus:outline-none focus:ring-0 outline-none"
          >
            {/* <BiChevronLeft size={20} /> */}
            Back
          </button>
        </div>

        {/* CARD CONTAINER */}
        <div className="
        w-full
        rounded-2xl
        !border !border-[var(--search-border)]
        py-2 px-2.5
      ">

          {/* FORM GRID */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">

            {/* USE CASE */}
            <div className="flex flex-col">
              <label className="text-sm font-medium text-[var(--text-color)]">
                Select UseCase Template <span className="text-red-500">*</span>
              </label>

              <Select
                value={
                  EmailData.useCaseTemplate !== "" &&
                  TemplateOptions.filter(
                    (item) => item.value === EmailData.useCaseTemplate
                  )
                }
                placeholder="Select Template"
                onChange={(e) => handleChangeSelect(e)}
                options={TemplateOptions}
                classNamePrefix="select"
                styles={{
                  control: (base) => ({
                    ...base,
                    backgroundColor: "var(--input-enable-bg)",
                    borderColor: "var(--input-enable-border)",
                  }),
                  menu: (base) => ({
                    ...base,
                    backgroundColor: "var(--input-enable-bg",
                  }),
                }}
              />
            </div>

            {/* TEMPLATE NAME */}
            <div className="flex flex-col">
              <label className="text-sm font-medium text-[var(--text-color)]">
                Email Template Name <span className="text-red-500">*</span>
              </label>

              <input
                name="TempletName"
                value={EmailData.TempletName}
                onChange={handleInput}
                disabled={!state?.copyData}
                className="
                w-full
                rounded-lg
                !border !border-[var(--input-enable-border)]
                h-[35px]
                bg-[var(--input-enable-bg)]
                px-2 py-1
                text-[13px]
                text-[var(--text-color)]
                focus:outline-none
                focus:ring
                focus:ring-[var(--input-onhover-border)]
              "
              />
            </div>

            {/* SUBJECT */}
            <div className="flex flex-col">
              <label className="text-sm font-medium text-[var(--text-color)]">
                Mail Subject <span className="text-red-500">*</span>
              </label>

              <input
                name="subject"
                value={EmailData.subject}
                onChange={handleInput}
                className="
                w-full
                rounded-lg
                !border !border-[var(--input-enable-border)]
                h-[35px]
                bg-[var(--input-enable-bg)]
                px-2
                text-[13px]
                text-[var(--text-color)]
                focus:outline-none
                focus:ring
                focus:ring-[var(--input-onhover-border)]
              "
              />
            </div>

            {/* RECIPIENTS */}
            <div className="flex flex-col">
              <label className="text-sm font-medium text-[var(--text-color)]">
                Recipients <span className="text-red-500">*</span>
              </label>

            {/* <div className="flex flex-wrap">
                {recipient.map((item) => (
                  <div
                    key={item}
                    className="
                    rounded-md
                    text-[12px] mb-[2px] px-1 mx-[1px]
                    bg-[var(--submit-button-bg)] text-[#111111]
                    !border !border-[var(--form-border)]
                  "
                  >
                    {item}
                  </div>
                ))}
              </div> */}

              <div className="flex flex-wrap gap-[2px]">
  {recipient.map((item) => (
    <div
      key={item}
      className="
      flex items-center gap-1
      rounded-md
      text-[12px] mb-[2px] px-1 mx-[1px]
      bg-[var(--submit-button-bg)] text-[#111111]
      !border !border-[var(--form-border)]
    "
    >
      <span>{item}</span>

      <button
        type="button"
        onClick={() => handleDeleteEmail(item)}
        className="
        text-[10px]
        font-extrabold
        text-black mt-[1px]
        ml-[2px] text-center
        cursor-pointer
      "
      >
        ✕
      </button>
    </div>
  ))}
</div>

              <input
                value={recipientInput}
                onKeyDown={handleKeyDownRecipient}
                onChange={handleChangeRecipientInput}
                placeholder="Type email and press Enter"
                className="
                w-full
                rounded-lg
                !border !border-[var(--input-enable-border)]
                h-[35px]
                bg-[var(--input-enable-bg)]
                px-2
                text-[var(--text-color)]
                focus:outline-none
                focus:ring
                focus:ring-[var(--input-onhover-border)]
                placeholder:text-[var(--search-placeholder)] placeholder:text-[13px]
              "
              />
                
            </div>
            
          </div>

          {/* NOTE SECTION */}
          <div className="mt-4 text-sm text-[var(--text-color)] space-y-2">
            <p>
              <strong>Note :</strong> Available Dynamic Parameters are as below.
              Include them like <span className="font-medium">{`{critical_limit}`}</span>
            </p>

            <div className="flex flex-wrap gap-2">
              {[
                "plant_name",
                "fan_name",
                "critical_limit",
                "timestamp",
                "current_efficiency",
                "current_speed",
                "current_load",
                "current_inlet",
                "current_outlet",
                "current_temp",
                "critical_percent",
              ].map((param) => (
                <span
                  key={param}
                  className="
                  px-2 py-1
                  rounded-md
                  text-xs
                  bg-[var(--table-row-hover)]
                  !border !border-[var(--form-border)]
                "
                >
                  {param}
                </span>
              ))}
            </div>
          </div>

          {/* TEMPLATE BODY */}
          <div className="mt-8">
            <label className="text-sm font-medium text-[var(--text-color)]">
              Template Body
            </label>

            <div className="mt-2 !border border-[var(--form-border)] rounded-lg overflow-hidden bg-none">
              <CKEditor
                editor={ClassicEditor}
                data={EditorData}
                onChange={(event, editor) =>
                  setEditorData(editor.getData())
                }
              />
            </div>
          </div>

          {/* SUBMIT BUTTON */}
          <div className="flex justify-center items-center mt-4">
            <button
              disabled={EmailData.TempletName === "" || submitLoader}
              onClick={SendData}
              className="
              px-2 py-1
            rounded-md
            !border border-[var(--button-border)]
            bg-[var(--submit-button-bg)]
            hover:bg-[var(--submit-button-hover-bg)]
            text-[#111111]
            transition-all duration-200
            disabled:opacity-50
            disabled:cursor-not-allowed
            cursor-pointer
            active:scale-95
            text-[14px]
            font-medium "
            >
              {state?.rowdata ? "Update Template" : "Submit Template"}
            </button>
          </div>
        </div>
      </div>
    </AuthenticatedTemplate>
  );

};
