export { NewCoalMillChilamkurL1Page } from "./New Coal Mill/NewCoalMillChilamkurL1Page";
export { OldCoalMillChilamkurL1Page } from "./Old Coal Mill/OldCoalMillChilamkurL1Page";
export { RollerPressChilamkurL1Page } from "./Roller Press/RollerPressChilamkurL1Page";
export { PreheaterChilmakurL1Page } from "./Preheater/PreheaterChilmakurLine1Page";
export { KilnChilmakurL1Page } from "./Kiln/KilnChilmakurL1Page";
export { CementMill1ChilmakurL1Page } from "./Cement Mill 1/CementMill1ChilmakurL1Page";
export { CementMill2ChilmakurL1Page } from "./Cement Mill 2/CementMill2ChilmakurL1Page";
export { CoolerChilmakurLine1Page } from "./Cooler/CoolerChilmakurLine1Page";
export { RawMill1ChilmakurLine1Page } from "./Raw Mill 1/RawMill1ChilmakurLine1Page";
export { RawMill2ChilmakurLine1Page } from "./Raw Mill 2/RawMill2ChilmakurLine1Page";
export { FineCoalTVRChilmakurLine1Page } from "./Fine Coal TVR/FineCoalTVRChilmakurLine1Page";