import "./UtilityRawanL2Page.scss";
import { ReactFlowProvider } from "reactflow";
import {
  UtilityRawanL2Nodes,
  UtilityRawanL2NodesType,
} from "../../../../../reactflow";
import { ReactFlowRenderer } from "../../../../../components/ReactFlowRenderer/ReactFlowRenderer";

export const UtilityRawanL2Page = () => {
  return (
    <ReactFlowProvider>
      <ReactFlowRenderer
        node={UtilityRawanL2Nodes}
        nodeType={UtilityRawanL2NodesType}
        plantDetails={{
          plantCode: "RWCW",
          plantName: "Rawan",
          sectionName: "General",
          section: "Raw Mill",
          line: "2",
          extraTagDetails: [
            {
              Section: "Coal Mill",
              Tags: ["WATER_INJECTION/DEW_POINT_TX", "PLC08/TTP", "PLC08/TTP1"],
            },
            {
              Section: "Raw Mill-3",
              Tags: ["UREAL04/PT", "UREAL04/PT4", "PLC04/TTP"],
            },
            {
              Section: "Kiln",
              Tags: [
                "442CP1/IA",
                "442CP1/RPM",
                "442CP2/IA",
                "PLC05/TTP",
                "PLC06/TTP",
                "PLC06/TTP1",
                "M32WP7/M01",
                "M32WP8/M01",
                "M32WP9/M01",
                "M32FN1_M01/M01",
                "M32FN2_M01/M01",
                "M32FN3_M01/M01",
                "442CP1/IA",
                "442CP1/RPM",
                "442CP2/IA",
                "PLC05/TTP",
                "PLC06/TTP",
                "PLC06/TTP1",
              ],
            },
            {
              Section: "Raw Mill-2",
              Tags: [
                "442CP5/IA",
                "442CP5/AIR_PRESSURE",
                "PLC03/TTP",
                "PLC03/CBA",
                "AC_RABH1/AMP",
                "AC_RABH1/IA",
              ],
            },
            {
              Section: "Cooler",
              Tags: ["PLC07/TTP"],
            },
            {
              Section: "Clinker Transport",
              Tags: ["AC_CCR/AHU_CCR1_AMP", "512CV1/V01"],
            },
            // {
            //   Section: "General",
            //   Tags: [
            //     "L93CV1/V01",
            //     "ANEMOMETER $CCR2/WIND_SPED",
            //     "AC_CCR/SCR_TEMP",
            //     "UREAL06/CHILLAR-1",
            //     "UREAL06/CHILLAR-2",
            //     "UREAL06/CHILLAR-3",
            //     "AC_CCR/WP1-II",
            //     "AC_CCR/WP1",
            //     "AC_CCR/WP2-II",
            //     "AC_CCR/WP2",
            //     "AC_CCR/WP3-II",
            //     "AC_CCR/WP3",
            //     "AC_CCR/AHU1-AMP",
            //     "AC_CCR/AHU1",
            //     "AC_CCR/AHU2-AMP",
            //     "AC_CCR/AHU2",
            //     "AC_CCR/AHU_CCR1",
            //     "AC_CCR/AHU_CCR2",
            //     "VAM_CHLR2/M01",
            //     "VAM_CHLR2/AMP",
            //     "VAM_CHLR1/M01",
            //     "VAM_CHLR1/AMP",
            //     "VAM_CEP1/M01",
            //     "VAM_CEP1/AMP",
            //     "VAM_CEP2/M02",
            //     "VAM_CEP2/AMP",
            //     "M22WP1/M01",
            //     "M22WP1/AMP",
            //     "M22WP2/M01",
            //     "M22WP2/AMP",
            //     "M22WP3/M01",
            //     "M22WP3/AMP",
            //     "M22WP4/M01",
            //     "M22WP4/AMP",
            //     "M22WP5/M01",
            //     "M22WP5/AMP",
            //     "M22WP6/M01",
            //     "M22WP6/AMP",
            //     "M32WP1/M01",
            //     "M32WP1/AMP",
            //     "M32WP2/M01",
            //     "M32WP2/AMP",
            //     "M32WP3/M01",
            //     "M32WP4/M01",
            //     "M32FN1_M01/COOLING_TWR_LVL-1",
            //     "M32FN1_M01/COOLING_TWR_LVL-2",
            //     "M42WP2/M01",
            //     "M42WP1/M01",
            //     "M32WP5/M01",
            //     "M32WP6/M01",
            //     "M52WP1/M01",
            //     "M52WP3/M01",
            //     "M52WP1PTX",
            //     "AHU_FAN_VFD_/M01",
            //     "M32FN_2/M01",
            //     "M32FN_3/M01",
            //   ],
            // },
            {
              Section: "PreHeater",
              Tags: [
                "442CP1/M01",
                "442AD1/442AD1",
                "442CP2/M02",
                "442AD2/442AD2",
                "442CP3/M01",
                "442AD3/442AD3",
                "442CP4/M01",
                "442AD4/442AD4",
                "442CP5/M02",
                "442AD5/442AD5",
                "PLC03/TTP1",
                "UREAL06/RABH_CHILLER1",
                "UREAL06/RABH_CHILLER2",
                "UREAL06/RABH_CHILLER3",
                "AC_RABH1/WP1",
                "AC_RABH1/WP2",
                "AC_RABH/AHU1",
                "AC_RABH/AHU2",
                "422WP1/M01",
                "422WP2/M01",
              ],
            },
            {
              Section: "Raw Mill",
              Tags: [
                "M32WP7/IA",
                "M32WP8/IA",
                "M32WP9/IA",
                "M32FN1_M01/WATER_TEMP",
                "M32FN1_M01/AMP",
                "M32FN2_M01/AMP",
                "M32FN3_M01/AMP",
                "442CP3/IA",
                "442CP4/IA",
                "442CP4/RPM",
                "PLC02/TTP",
                "AC_RABH/IA",
                "AC_RABH/AMP",
              ],
            },
          ],
        }}
      />
    </ReactFlowProvider>
  );
};
