import json
from datetime import datetime, timezone, timedelta
import concurrent.futures
import logging, time
import pandas as pd
import boto3
from boto3.dynamodb.conditions import Key, Attr
from mail_alert_support_module import *
import warnings
warnings.filterwarnings("ignore")
import pyodbc
import os
# Configure logging
logging.basicConfig(level=logging.INFO, 
                   format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Suppress boto3/botocore logging
logging.getLogger('botocore').setLevel(logging.ERROR)
logging.getLogger('boto3').setLevel(logging.ERROR)
logging.getLogger('urllib3').setLevel(logging.ERROR)

# Environment variables
database = os.getenv("database")
password = os.getenv("password")
username = os.getenv("username")
server = os.getenv("server") 

# Initialize AWS clients
session = boto3.session.Session(region_name='ap-south-1')
dynamodb = session.resource('dynamodb')

def fetch_mail_template_info(query) -> pd.DataFrame:
    # """
    # Return mock data for email templates.
    # """
    # logger.info("Using mock data for email templates")
    
    # # Create mock data based on the examples you provided
    # mock_data = {
    #     'Timestamp': [datetime(2023, 3, 14, 12, 41, 0, 120000)],
    #     'UserId': ['utcl-mum.brm5@adityabirla.com'],
    #     'EmailTemplateName': ['Fan Efficiency Alert'],
    #     'Subject': [
    #         'GCW-{fan_name} Efficiency {critical_percent}% - Critical'
    #     ],
    #     'UseCaseTemplate': ['GCW_L1_Calciner_String'],
    #     'Recipients': ['sambarora@deloitte.com@@@akash.chakraborty@celebaltech.com'],
    #     'Description': [
    #         '<style>table, th, td {border: 1px solid black;border-collapse: collapse}</style><p><strong>Description</strong>:<br>Following information generated by automated system.<br>&nbsp;</p><p>Fan {fan_name} efficiency has dropped by {critical_percent}%.</p><p>Current efficiency: {current_efficiency}%</p><p>Current speed: {current_speed} RPM</p><p>Current load: {current_load} kW</p><p>Current inlet draft: {current_inlet} mmWC</p><p>Current outlet draft: {current_outlet} mmWC</p><p>Current temperature: {current_temp} °C</p><p>Time: {current_time}</p>'
    #     ]
    # }
    
    # return pd.DataFrame(mock_data)

    driver = '{ODBC Driver 17 for SQL Server}'
    dbconnection = 'DRIVER='+driver+';SERVER=tcp:'+server+';PORT=1433;DATABASE='+database+';UID='+username+';PWD='+ password
    try:
        with pyodbc.connect(dbconnection) as conn:
            with conn.cursor() as cursor:
                cursor.execute(query)
                rows = cursor.fetchall()
                columns = [column[0] for column in cursor.description]
                df = pd.DataFrame([tuple(row) for row in rows], columns=columns)

        if df.empty:
            raise Exception(f'SapBlaine data is not available for the give parameters.')
        return df

    except Exception as e:
        raise Exception(f'Exception occurred while executing stored procedure: {e}')


def fetch_template_info(query) -> pd.DataFrame:
    # """
    # Return mock data for equipment templates.
    # """
    # logger.info("Using mock data for equipment templates")
    
    # # Create mock data for equipment templates based on real data
    # mock_data = {
    #     'TemplateName': ['GCW_L1_Calciner_String'],
    #     'PlantName': ['GCW'],
    #     'FanName': ['GCW_L1_Calciner_String-Fan'],
    #     'Parameters': [
    #         '{"Speed":"100" @@@"Load":"200"@@@"Inlet Draft":"300" @@@"Outlet Draft":"400" @@@"Temperature":"250"@@@"SPRS":"0.5"@@@"Designed Flow(m3!s)":"208" @@@"Designed Temp(degC)":"253" @@@"Designed Speed(RPM)":"940" @@@"Designed Load(KWh)":"2538" @@@"Designed Head(mmwc)":"1052"}'
    #     ],
    #     'Conditions': [
    #         '{"Min":"5" @@@"Max":"10"@@@"Duration":"10"}'
    #     ],
    #     'UseCase': ['Fan Efficiency'],
    #     'Status': ['Active'],
    #     'UserId': [
    #         'utcl-mum.brm5@adityabirla.com'
    #     ]
    # }
    
    # return pd.DataFrame(mock_data)
    driver = '{ODBC Driver 17 for SQL Server}'
    dbconnection = 'DRIVER='+driver+';SERVER=tcp:'+server+';PORT=1433;DATABASE='+database+';UID='+username+';PWD='+ password
    try:
        with pyodbc.connect(dbconnection) as conn:
            with conn.cursor() as cursor:
                cursor.execute(query)
                rows = cursor.fetchall()
                columns = [column[0] for column in cursor.description]
                df = pd.DataFrame([tuple(row) for row in rows], columns=columns)

        if df.empty:
            raise Exception(f'Error occurred while fetching the template info')
        return df

    except Exception as e:
        raise Exception(f'Exception occurred while executing stored procedure: {e}')


def df_from_dynamo(query_string):
    """
    Replacement for df_from_adx to fetch data from DynamoDB
    """
    try:
        # Parse the query to extract necessary parameters
        table_name = query_string.split('|')[0].strip()
        table = dynamodb.Table(table_name)
        
        conditions = query_string.split('|')[1] if '|' in query_string else ""
        
        # Extract template names
        template_list = []
        if "TemplateName in" in conditions:
            template_str = conditions.split("TemplateName in")[1].split("and")[0].strip()
            template_list = eval(template_str)
        
        # Extract time range
        minutes_ago = 30
        if "Timestamp>ago(" in conditions:
            time_part = conditions.split("Timestamp>ago(")[1].split(")")[0]
            if "m" in time_part:
                minutes_ago = int(time_part.split("m")[0])
        
        # Compute time threshold
        time_threshold = (datetime.utcnow() - timedelta(minutes=minutes_ago)).strftime('%Y-%m-%dT%H:%M:%S')
        logger.info(f"Using time threshold for {table_name}: {time_threshold}")
        
        items = []
        if template_list:
            for template in template_list:
                response = table.scan(
                    FilterExpression=Attr('TemplateName').eq(template) & Attr('Timestamp').gt(time_threshold)
                )
                items.extend(response.get('Items', []))
                
                while 'LastEvaluatedKey' in response:
                    response = table.scan(
                        FilterExpression=Attr('TemplateName').eq(template) & Attr('Timestamp').gt(time_threshold),
                        ExclusiveStartKey=response['LastEvaluatedKey']
                    )
                    items.extend(response.get('Items', []))
        else:
            response = table.scan(
                FilterExpression=Attr('Timestamp').gt(time_threshold)
            )
            items = response.get('Items', [])
            
            while 'LastEvaluatedKey' in response:
                response = table.scan(
                    FilterExpression=Attr('Timestamp').gt(time_threshold),
                    ExclusiveStartKey=response['LastEvaluatedKey']
                )
                items.extend(response.get('Items', []))

        logging.info(f"Scanned {len(items)} items from DynamoDB table '{table_name}'")
        if items:
            logging.debug(f"Sample item: {items[0]}")

        # Filter out items missing 'Timestamp'
        items = [item for item in items if 'Timestamp' in item]
        if not items:
            logging.warning("No items with 'Timestamp' found in scanned results.")
            return pd.DataFrame()

        df = pd.DataFrame(items)
        # Handle invalid timestamps
        def safe_parse_timestamp(ts):
            try:
                # Fix common timestamp issues
                if isinstance(ts, str) and ts.startswith('24:'):
                    ts = '00:' + ts[3:]  # Replace 24: with 00:
                return pd.to_datetime(ts, errors='coerce')
            except:
                # Return a default timestamp if parsing fails
                return pd.NaT
        
        # Apply the safe parsing function to the Timestamp column
        df['Timestamp'] = df['Timestamp'].apply(safe_parse_timestamp)
        
        # Drop rows with invalid timestamps
        df = df.dropna(subset=['Timestamp'])

        if "order by Timestamp desc" in query_string:
            df = df.sort_values(by='Timestamp', ascending=False)
            
        return df
    except Exception as e:
        logging.error(f'Exception occurred while fetching data from DynamoDB: {e}')
        raise


def fan_efficiency_mail_alert_trigger_main(event,context):
    """Main function for fan efficiency mail alert trigger"""
    utc_timestamp = datetime.utcnow().replace(
            tzinfo=timezone.utc).isoformat()
    logger.info(f"Starting fan efficiency mail alert trigger at {utc_timestamp}")

    start_time = time.time()
    try:
        # Fetch active templates from SQL Server
        ui_data_query = "select * from [dbo].[CBM_EquipmentTemplates] where Status = 'Active' and UseCase = 'Fan Efficiency'"
        ui_active_template = fetch_template_info(ui_data_query)
        logger.info(f"Found {len(ui_active_template)} active templates")

        template_list = tuple(ui_active_template['TemplateName'].unique())
        logger.info(f"Template names: {template_list}")
        

        # Query DynamoDB for efficiency data
        logger.info("Fetching average efficiency data from DynamoDB...")
        avg_efficiency_df_query = f'Utcl_CBM_Fan_AverageEfficiency_Testing|where TemplateName in {template_list} and Timestamp>ago(30m)+330m|order by Timestamp desc'
        main_avg_efficiency_df = df_from_dynamo(avg_efficiency_df_query)
        logger.info(f"Retrieved {len(main_avg_efficiency_df)} average efficiency records")
        
        logger.info("Fetching current efficiency data from DynamoDB...")
        main_table_query = f'Utcl_CBM_Fan_Efficiency_Testing|where TemplateName in {template_list} and Timestamp>ago(10m)+330m|order by Timestamp desc'
        main_efficiency_df = df_from_dynamo(main_table_query)
        logger.info(f"Retrieved {len(main_efficiency_df)} current efficiency records")
        
        # Fetch email templates from SQL Server
        logger.info("Fetching email templates from SQL Server...")
        formatted_templates = ', '.join(f"'{item}'" for item in template_list)
        mail_template_query = f"select * from [dbo].[CBM_EmailTemplates] where UseCaseTemplate in ({formatted_templates})"
        mail_template_df = fetch_mail_template_info(mail_template_query)
        logger.info(f"Retrieved {len(mail_template_df)} email templates")

    except Exception as e:
         raise Exception(f'{e}')
    
    logger.info("Processing templates...")
    with concurrent.futures.ThreadPoolExecutor() as executor:      
            for i in range(len(ui_active_template)):
                try:
                    template = ui_active_template.loc[i] # selecting current template df
                    template_name = template['TemplateName']
                    logger.info(f"Processing template: {template_name}")

                    equipment_name = template['FanName']
                    plant_name = template['PlantName']
                    user_id = template['UserId']

                    logger.info(f"Fetching conditions for {template_name}...")
                    thread1 = executor.submit(fetch_conditions,[template,template_name,main_avg_efficiency_df])
                    avg_efficiency_df,duration,efficiency_drop,current_time = thread1.result()
                    logger.info(f"Conditions: duration={duration}, efficiency_drop={efficiency_drop:.2%}")

                    logger.info(f"Fetching fan data for {template_name}...")
                    thread2 = executor.submit(fetch_fan_data,[template_name,main_efficiency_df])
                    current_speed,current_load,inlet_draft,outlet_draft,current_temperature,efficiency = thread2.result()
                    logger.info(f"Fan data: speed={current_speed}, load={current_load}, efficiency={efficiency:.2%}")
                    
                    logger.info(f"Fetching mail data for {template_name}...")
                    thread3 = executor.submit(fetch_mail_data,[template_name,mail_template_df])
                    subject,recipients_list,body_string = thread3.result()
                    logger.info(f"Mail data: recipients={recipients_list}, subject={subject[:30]}...")
                    
                    subject = subject.format(fan_name=equipment_name,critical_percent=round(efficiency_drop*100,2),plant_name=plant_name)
                    body = body_string.format(
                        fan_name=equipment_name,
                        critical_percent=round(efficiency_drop*100,2),
                        current_time=datetime.strftime(current_time,'%d/%m/%y %H:%M:%S'),
                        current_efficiency=efficiency*100,
                        current_speed=current_speed,
                        current_load=current_load,
                        current_inlet=inlet_draft,
                        current_outlet=outlet_draft,
                        current_temp=current_temperature
                    )                        
                    logger.info(f"Checking alert conditions for {template_name}...")
                    thread4 = executor.submit(alert_mechanism,[template_name,avg_efficiency_df,duration,recipients_list,subject,body,current_time,user_id])
                    final_output = thread4.result()
                    logger.info(f"Alert result for {template_name}: {final_output}")

                except Exception as e:
                    logging.error(f"Error processing template {template_name}: {e}")
                    print(e)  
            
    end_time=time.time()
    execution_time = end_time-start_time
    logger.info(f'Execution completed in {execution_time:.1f} seconds')
