import {
  GrayDot,
  GrayDotWithText,
  ImageData,
  BlackDotWithGreenBroder,
  GreenDot,
  GreenDotWithText,
  PinkDot,
  BlackCross,
  BlankContainer,
  HPipeCircle,
  HPipeCircleRed,
  HPipeCircleReverse,
  HPipeCircleWithoutRight,
  LeftContainer,
  TextContainer,
  BlackContainer,
  TextData,
  TextContainerWithWrapWord,
  DownArrow,
  BoxContainer,
  BoxContainerMiddleTable,
  BoxContainerTable,
  BoxContainerTableWithTopLabel,
  Squrebox,
  HorizontalLine,
  VerticallLine,
  CGrnBox1,
  CGrnBox2,
} from "../../../../components";

export const nodeTypeNew = {
  "text-container": TextContainer,
  "black-container": BlackContainer,
  greendot: GreenDot,
  pinkdot: PinkDot,
  "black-dot-with-green-border": BlackDotWithGreenBroder,
  "left-container": LeftContainer,
  "h-pipe-circle": HPipeCircle,
  "h-pipe-circle-without-right": HPipeCircleWithoutRight,
  graydot: GrayDot,
  "text-data": TextData,
  "black-cross": BlackCross,
  "image-data": ImageData,
  "down-arrow": DownArrow,
  "h-pipe-circle-reverse": HPipeCircleReverse,
  "h-pipe-circle-red": HPipeCircleRed,
  "text-container-with-wrap-word": TextContainerWithWrapWord,
  "box-container": BoxContainer,
  "blank-container": BlankContainer,
  squrebox: Squrebox,
  "box-container-table": BoxContainerTable,
  "horizontal-line": HorizontalLine,
  "vertical-line": VerticallLine,
  "greendot-with-text": GreenDotWithText,
  "graydot-with-text": GrayDotWithText,
  "box-container-middle-table": BoxContainerMiddleTable,
  "box-container-table-with-label": BoxContainerTableWithTopLabel,
  "c-grn-box-1": CGrnBox1,
  "c-grn-box-2": CGrnBox2,
};
