import "./PreheaterKilnHirmiL2Page.scss";
import { ReactFlowProvider } from "reactflow";
import {
  PreheaterKilnHirmiL2Nodes,
  PreheaterKilnHirmiL2NodesType,
} from "../../../../../reactflow";
import { ReactFlowRenderer } from "../../../../../components/ReactFlowRenderer/ReactFlowRenderer";

export const PreheaterKilnHirmiL2Page = () => {
  return (
    <ReactFlowProvider>
      <ReactFlowRenderer
        node={PreheaterKilnHirmiL2Nodes}
        nodeType={PreheaterKilnHirmiL2NodesType}
        plantDetails={{
          plantCode: "HCW",
          plantName: "Hirmi",
          sectionName: "PreHeater",
          section: "Preheater Kiln",
          line: "2",
          extraTagDetails: [
            {
              Section: "Kiln", // 56 occurrences
              Tags: [
                "KL_452DG1_SPSPA",
                "KL_PROL_TEMP",
                "KL_452DG1_SPSPM",
                "W2_442SD2_M01",
                "KL_462AD1_ONTM",
                "KL_462AD1_OFFTM",
                "KL_462MD1AI01",
                "KL_452FN1",
                "KL_462KT1_ZT1",
                "KL_462MD1_SPC_PWR",
                "KL_462TV1_TT3_OPC",
                "KL_462KL1_FILL",
                "KL_462KL1_RTTM",
                "KL_462MD1_JI",
                "KL_462MD1_SPSPM",
                "PH_462AM1_O2",
                "KL_FEED_TODAY_TOTAL_DISPLAY",
                "PH_432DQ1_SPSPM",
                "PH_432FM1_SPSPM",
                "KL_482DQ1_MB_PRCNT",
                "KL_482DQ1_PC_PRCNT",
                "KL_482_CONSUMPTION",
                "KL_452DQ2_SPSPA",
                "KL_452DQ2_SPSPM",
                "KL_482DQ1_SPSPM",
                "KL_482BL1_SPSPM",
                "KL_482BL2_SPSPM",
                "KL_482BL4_SPSPM",
                "KL_482BL3_SPSPM",
                "KL_PRODUCTION_SP",
                "KL_CLINKER_PROD_TPD",
                "KL_452BI1_WI",
                "KL_452BI2_WI",
                "KL_452DQ1",
                "KL_452DQ1_FR",
                "KL_452DQ1_MC_II",
                "KL_452DQ1_MC_SI",
                "KL_452DQ2",
                "KL_452DQ2_FR",
                "KL_452DQ2_MC_II",
                "KL_452DQ2_MC_SI",
                "KL_462AD1_M01",
                "KL_462AD1_M01II_B",
                "KL_462AD1_M02",
                "KL_462DU1_PT1",
                "KL_462DU1_TT1",
                "KL_462FN7",
                "KL_462FN7_PT1",
                "KL_462FN8",
                "KL_462FN8_PT1",
                "KL_462FN9",
                "KL_462FNQ",
                "KL_462KL1_PT3",
                "KL_462KL1_TT4",
                "KL_462MD1_II",
                "KL_462MD1_SI",
                "KL_462MD1_TRIP_CNT",
                "KL_482BI1_WI",
                "KL_482BL1",
                "KL_482BL1_2_PT",
                "KL_482BL1_II",
                "KL_482BL1_PT",
                "KL_482BL1_SI",
                "KL_482BL2",
                "KL_482BL2_II",
                "KL_482BL2_PT",
                "KL_482BL2_SI",
                "KL_482BL3",
                "KL_482BL3_4_PT",
                "KL_482BL3_II",
                "KL_482BL3_PT",
                "KL_482BL3_SI",
                "KL_482BL4_II",
                "KL_482BL4_PT",
                "KL_482BL4_SI",
                "KL_482BU1_PT3",
                "KL_482BV1",
                "KL_482BV2",
                "KL_482BV3",
                "KL_482BV4",
                "KL_482BV5",
                "KL_482DQ1",
                "KL_482DQ1_FR",
                "KL_482DQ1_MC_II",
                "KL_482DQ1_MC_SI",
                "KL_482FP1",
                "KL_482FP2",
                "KL_482FT1_LT",
                "KL_482PO1_FT",
              ],
            },
            {
              Section: "Cooler", // 8 occurrences
              Tags: [
                "CL_492DB2II_B",
                "CL_492DB1II_B",
                "CL_472CC1_SI",
                "CL_472WP_PTA9",
                "CL_472WP_SP",
                "CL_492DB1",
                "CL_492DB2",
                "CL_492SI1_LT1",
              ],
            },
          ],
        }}
      />
    </ReactFlowProvider>
  );
};
