export const nodesNew = [
  {
    id: "1000",
    type: "left-container",
    data: {
      label: "311RE1",
      useClass: "yellowTxt",
      Children: [
        {
          label: "311RE1_CHAIN",
          useClass: "greenTxt",
          unit: "A",
          unitColor: "unitColor",
        },
        {
          label: "311RE1_HARROW",
          useClass: "greenTxt",
          unit: "A",
          unitColor: "unitColor",
        },
      ],
    },
    position: { x: 0, y: 0 },
    className: "yellowTxt id-1000",
  },
  {
    id: "2",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-2",
  },
  {
    id: "3",
    type: "h-pipe-circle",
    data: { label: "311BC1", useClass: "blackTxt p-1" },
    position: { x: 0, y: 0 },
    className: "id-3",
  },
  {
    id: "4",
    type: "h-pipe-circle",
    data: { label: "311BC2", useClass: "blackTxt p-1" },
    position: { x: 0, y: 0 },
    className: "id-4",
  },
  {
    id: "5",
    type: "h-pipe-circle",
    data: { label: "311BC4", useClass: "blackTxt p-1", useblackcross: true },
    position: { x: 0, y: 0 },
    className: "id-5",
  },

  {
    id: "6",
    type: "text-container",
    data: { label: "241CR1", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-6",
  },
  {
    id: "7",
    type: "image-data",
    data: {
      label: null,
      useClass: "topImage",
      size: { width: "30px", height: "30px", backgroundSize: "cover" },
      subImage: "redCircle",
    },
    position: { x: 0, y: 0 },
    className: "id-7",
  },
  {
    id: "8",
    type: "h-pipe-circle-reverse",
    data: {
      label: "",
      circleLabel: "241BC2-MK",
      useClass: "blackTxt p-1",
      useStyle: { width: "90px" },
      useblackcross: true,
    },
    position: { x: 0, y: 0 },
    className: "id-8",
  },
  {
    id: "9",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "11px" } },
    position: { x: 0, y: 0 },
    className: "id-9",
  },

  {
    id: "10",
    type: "h-pipe-circle-reverse",
    data: {
      label: "",
      useClass: "blackTxt p-1",
      useblackcross: true,
      useStyle: { width: "90px" },
    },
    position: { x: 0, y: 0 },
    className: "id-10",
  },
  {
    id: "11",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "18px" } },
    position: { x: 0, y: 0 },
    className: "id-11",
  },
  {
    id: "12",
    type: "h-pipe-circle-red",
    data: { label: null, useStyle: { top: "0px" } },
    position: { x: 0, y: 0 },
    className: "id-12",
  },
  {
    id: "13",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "11px" } },
    position: { x: 0, y: 0 },
    className: "id-13",
  },

  {
    id: "14",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "11px" } },
    position: { x: 0, y: 0 },
    className: "id-14",
  },

  {
    id: "15",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "11px" } },
    position: { x: 0, y: 0 },
    className: "id-15",
  },

  {
    id: "16",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "11px" } },
    position: { x: 0, y: 0 },
    className: "id-16",
  },
  {
    id: "17",
    type: "image-data",
    data: {
      label: null,
      useClass: "containerImage",
      size: { backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-17",
  },
  {
    id: "18",
    type: "image-data",
    data: {
      label: null,
      useClass: "containerImage",
      size: { backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-18",
  },
  {
    id: "19",
    type: "image-data",
    data: {
      label: null,
      useClass: "containerImage",
      size: { backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-19",
  },
  {
    id: "20",
    type: "image-data",
    data: {
      label: null,
      useClass: "containerImage",
      size: { backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-20",
  },
  {
    id: "21",
    type: "h-pipe-circle",
    data: { label: "311WF1", useClass: "blackTxt p-1" },
    position: { x: 0, y: 0 },
    className: "id-21",
  },
  {
    id: "22",
    type: "h-pipe-circle",
    data: { label: "311WF3", useClass: "blackTxt p-1" },
    position: { x: 0, y: 0 },
    className: "id-22",
  },
  {
    id: "23",
    type: "h-pipe-circle",
    data: { label: "311WF2", useClass: "blackTxt p-1" },
    position: { x: 0, y: 0 },
    className: "id-23",
  },
  {
    id: "24",
    type: "h-pipe-circle",
    data: { label: "311WF4", useClass: "blackTxt p-1" },
    position: { x: 0, y: 0 },
    className: "id-24",
  },
  {
    id: "25",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "19px" } },
    position: { x: 0, y: 0 },
    className: "id-25",
  },
  {
    id: "26",

    type: "text-container-with-wrap-word",
    data: { label: "Lime stone 1", useClass: "wrapTextDiv" },
    position: { x: 0, y: 0 },
    className: "id-26",
  },
  {
    id: "27",

    type: "text-container-with-wrap-word",
    data: { label: "Lime stone 2", useClass: "wrapTextDiv" },
    position: { x: 0, y: 0 },
    className: "id-27",
  },
  {
    id: "28",

    type: "text-container-with-wrap-word",
    data: { label: "Ironore Phy Lite", useClass: "wrapTextDiv" },
    position: { x: 0, y: 0 },
    className: "id-28",
  },
  {
    id: "29",

    type: "text-container-with-wrap-word",
    data: { label: "Silica Sweet", useClass: "wrapTextDiv" },
    position: { x: 0, y: 0 },
    className: "id-29",
  },
  {
    id: "30",

    type: "black-container",
    data: {
      label: "311HP1-LZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "M",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-30",
  },
  {
    id: "31",

    type: "black-container",
    data: {
      label: "311HP2-LZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "M",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-31",
  },
  {
    id: "32",

    type: "black-container",
    data: {
      label: "311HP3LZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "M",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-32",
  },
  {
    id: "33",

    type: "black-container",
    data: {
      label: "311HP4LZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "M",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-33",
  },

  {
    id: "34",

    type: "black-container",
    data: {
      label: "331WF1_MAN:MV",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-34",
  },
  {
    id: "35",

    type: "black-container",
    data: {
      label: "331WF2_MAN:MV",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-35",
  },
  {
    id: "36",

    type: "black-container",
    data: {
      label: "331WF3_MAN:MV",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-36",
  },
  {
    id: "37",

    type: "black-container",
    data: {
      label: "331WF4-AO",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-37",
  },

  {
    id: "38",

    type: "black-container",
    data: {
      label: "331WF1-FZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "TPH",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-38",
  },
  {
    id: "39",

    type: "black-container",
    data: {
      label: "331WF2-FZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "TPH",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-39",
  },
  {
    id: "40",

    type: "black-container",
    data: {
      label: "331WF3FZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "TPH",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-40",
  },
  {
    id: "41",

    type: "black-container",
    data: {
      label: "331WF4FZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "TPH",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-41",
  },
  {
    id: "42",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "40px" } },
    position: { x: 0, y: 0 },
    className: "id-42",
  },
  {
    id: "43",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "40px" } },
    position: { x: 0, y: 0 },
    className: "id-43",
  },
  {
    id: "44",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "40px" } },
    position: { x: 0, y: 0 },
    className: "id-44",
  },
  {
    id: "45",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "40px" } },
    position: { x: 0, y: 0 },
    className: "id-45",
  },
  {
    id: "46",
    type: "h-pipe-circle",
    data: { label: "331BC1", useClass: "blackTxt p-1 mw-325" },
    position: { x: 0, y: 0 },
    className: "id-46",
  },
  {
    id: "47",
    type: "box-container",
    data: {
      label: "331BC1",
      useClass: "blackTxt p-1 mw-60",
      Children: [
        { label: "331BC1_MAN", useClass: "greenTxt" },
        {
          label: "331BC1SZ1",
          useClass: "greenTxt",
          unit: "RPM",
          unitColor: "unitColor",
        },
        {
          label: "331BC1IZ1",
          useClass: "greenTxt",
          unit: "A",
          unitColor: "unitColor",
        },
      ],
    },
    position: { x: 0, y: 0 },
    className: "id-47",
  },
  {
    id: "48",
    type: "blank-container",
    data: {
      label: "",
      useStyle: "h",
    },
    position: { x: 0, y: 0 },
    className: "id-48",
  },
  {
    id: "49",
    type: "box-container",
    data: {
      label: "",
      useClass: "blackTxt p-1 mw-60",
      Children: [
        {
          label: "361MD2JZ1",
          useClass: "greenTxt",
          unit: "KW",
          unitColor: "unitColor",
        },
        {
          label: "361MD2IZ1",
          useClass: "greenTxt",
          unit: "A",
          unitColor: "unitColor",
        },
      ],
    },
    position: { x: 0, y: 0 },
    className: "id-49",
  },
  {
    id: "50",
    type: "h-pipe-circle",
    data: { label: "331BC2", useClass: "blackTxt p-1 mw-170" },
    position: { x: 0, y: 0 },
    className: "id-50",
  },
  {
    id: "51",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-51",
  },
  {
    id: "52",
    type: "vertical-line",
    data: {
      label: "",
      useClass: "yellowline-Hr",
      useStyle: { width: "3px", height: "18px" },
    },
    position: { x: 0, y: 0 },
    className: "id-52",
  },
  {
    id: "53",

    type: "down-arrow",
    data: { label: null, useStyle: { height: "55px" } },
    position: { x: 0, y: 0 },
    className: "id-53",
  },
  {
    id: "54",
    type: "h-pipe-circle",
    data: { label: "361BC2", useClass: "blackTxt p-1 mw-170" },
    position: { x: 0, y: 0 },
    className: "id-54",
  },
  {
    id: "55",

    type: "black-container",
    data: {
      label: "361FD1IZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "A",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-55",
  },
  {
    id: "56",

    type: "image-data",
    data: {
      label: null,
      useClass: "triangle-with-squares",
      size: { width: "53px", height: "60px", backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-56",
  },
  {
    id: "57",

    type: "down-arrow",
    data: { label: null, useStyle: { height: "25px" } },
    position: { x: 0, y: 0 },
    className: "id-57",
  },
  {
    id: "58",
    type: "box-container",
    data: {
      label: "",
      useClass: "blackTxt p-1 mw-60",
      Children: [
        { label: "361WP1_PID:MV", useClass: "greenTxt" },
        {
          label: "361VM2ZZ1",
          useClass: "greenTxt",
          unit: "%",
          unitColor: "unitColor",
        },
        {
          label: "361WI1-SP",
          useClass: "greenTxt",
          unit: "M3/H",
          unitColor: "unitColor",
        },
        {
          label: "361WI1-FZ1",
          useClass: "greenTxt",
          unit: "M3/H",
          unitColor: "unitColor",
        },
      ],
    },
    position: { x: 0, y: 0 },
    className: "id-58",
  },
  {
    id: "59",
    type: "text-container",
    data: {
      label: "361MS1",
      useClass: "yellowTxt",
    },
    position: { x: 0, y: 0 },
    className: "yellowTxt id-59",
  },
  {
    id: "60",
    type: "pinkdot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-60",
  },
  {
    id: "61",
    type: "h-pipe-circle",
    data: { label: "361BC1", useClass: "blackTxt p-1 mw-60" },
    position: { x: 0, y: 0 },
    className: "id-61",
  },
  {
    id: "62",

    type: "black-container",
    data: {
      label: "361BW1-FZ1",
      useClass: "greenTxt mw-60",
      unit: "TPH",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-62",
  },
  {
    id: "63",
    type: "h-pipe-circle-without-right",
    data: {
      label: "361VF1",
      useStyle: { width: "238px" },
      useClass: "blackTxt p-1 mw-60",
    },
    position: { x: 0, y: 0 },
    className: "id-63",
  },
  {
    id: "64",

    type: "black-container",
    data: {
      label: "361VF1IZ1",
      useClass: "greenTxt mw-60",
      unit: "A",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-64",
  },
  {
    id: "65",

    type: "black-container",
    data: {
      label: "361VF1IZ2",
      useClass: "greenTxt mw-60",
      unit: "A",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-65",
  },
  {
    id: "66",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "11px" } },
    position: { x: 0, y: 0 },
    className: "id-66",
  },

  {
    id: "67",
    type: "black-container",
    data: {
      label: "241CR1TZ1",
      useClass: "greenTxt mw-60",
      unit: "C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-67",
  },
  {
    id: "68",
    type: "black-container",
    data: {
      label: "241CR1TZ2",
      useClass: "greenTxt mw-60",
      unit: "C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-68",
  },
  {
    id: "69",
    type: "box-container",
    data: {
      label: "LS PILE CONS TOT",
      useClass: "blackTxt p-1 mw-60",

      Children: [
        // Sea-green text will appear here--- LS PILE CONS TOT
        // Squares to be shown
        {
          label: "PILE1A-TOT",
          useClass: "greenTxt hasSqure",
          unit: "T",
          unitColor: "unitColor",
          squrebox: true,
          squreboxClass: "graySqure",
        },
        {
          label: "PILE1B-TOT",
          useClass: "greenTxt hasSqure",

          unit: "T",
          unitColor: "unitColor",
          squrebox: true,
          squreboxClass: "greenSqure",
        },
      ],
    },
    position: { x: 0, y: 0 },
    className: "id-69",
  },
  {
    id: "70",
    type: "black-container",
    data: { label: "331BC2_MAN:MV", useClass: "greenTxt mw-60", unit: "" },
    position: { x: 0, y: 0 },
    className: "id-70",
  },
  {
    id: "71",
    type: "black-container",
    data: {
      label: "331BC2SZ1",
      useClass: "greenTxt mw-60",
      unit: "RPM",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-71",
  },
  {
    id: "72",
    type: "black-container",
    data: {
      label: "331BC2IZ1",
      useClass: "greenTxt mw-60",
      unit: "A",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-72",
  },
  {
    id: "73",
    type: "down-arrow",
    data: {
      label: null,
      useStyle: { height: "26px", transform: "rotate(-23deg)" },
    },
    position: { x: 0, y: 0 },
    className: "id-73",
  },
  {
    id: "74",
    type: "image-data",
    data: {
      label: null,
      useClass: "icon6block",
      size: { width: "75px", height: "60px", backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-74",
  },
  {
    id: "75",
    type: "down-arrow",
    data: {
      label: null,
      useStyle: { height: "45px", transform: "rotate(60deg)" },
    },
    position: { x: 0, y: 0 },
    className: "id-75",
  },
  {
    id: "76",
    type: "down-arrow",
    data: {
      label: null,
      useStyle: { height: "45px", transform: "rotate(-60deg)" },
    },
    position: { x: 0, y: 0 },
    className: "id-76",
  },
  //   {
  //     id: "77",
  //     type: "text-container",
  //     data: { label: "361FD1", useClass: "yellowTxt" },
  //     position: { x: 0, y: 0 },
  //     className: "id-77",
  //   },
  {
    id: "78",
    type: "image-data",
    data: {
      label: null,
      useClass: "c-grn-pipes",
      size: { backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-78",
  },
  {
    id: "79",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-79",
  },
  {
    id: "80",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-80",
  },
  {
    id: "81",
    type: "text-container",
    data: { label: "361WP2", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-81",
  },
  {
    id: "82",
    type: "text-container",
    data: { label: "361WP1", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-82",
  },
  {
    id: "89",
    type: "box-container-table",
    data: {
      label: "",
      useClass: "yellowTxt p-1 mw-60",
      Children: [
        {
          label: "Winding",
          useClass: "yellowTxt",
          dataLabel: [
            {
              label: "3611X2TZ1",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "3611X2TZ2",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "3611X2TZ4",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "361FN1",
              usetype: "text-container",
              unit: "C",
              useClass: "yellowTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "361LD1_PID",
              unit: "RPM",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
        {
          label: " ",
          dataLabel: [
            {
              label: "3611X2TZ3",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "3611X2TZ5",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "3611X2TZ6",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "361FN1_SPEEDS.P.",
              unit: "%",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "361FN1SZ1",
              unit: "%",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
        {
          label: "MTR Brng",
          dataLabel: [
            {
              label: "3611X2TZ7",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "3611X2TZ8",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {},
            {
              label: "361FN1IZ1",
              unit: "A",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "361FN1JZ1",
              unit: "KW",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },

        {
          label: "Stator Core",
          dataLabel: [
            {
              label: "3611X2TZ9",

              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "3611X2TZA",

              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "3611X2TZB",

              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "361FN1AZ2",

              unit: "MM/S",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "361FN1AZ1",

              unit: "mm/s",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
        {
          label: "Fan Bearing",
          dataLabel: [
            {
              label: "361FN1TZ1",

              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "361FN1-TZ2",

              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {},
            {
              label: "361FN1TZ1",

              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "361FN1-TZ2",

              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
      ],
    },
    position: { x: 0, y: 0 },
    className: "id-89",
  },
  {
    id: "90",
    type: "horizontal-line",
    data: { label: "", useClass: "pipeHr pipeMiddleHr" },
    position: { x: 0, y: 0 },
    className: "id-90",
  },
  {
    id: "91",
    type: "vertical-line",
    data: { label: "", useClass: "pipeVr pipeMiddleVr" },
    position: { x: 0, y: 0 },
    className: "id-91",
  },
  {
    id: "92",
    type: "image-data",
    data: {
      label: null,
      useClass: "bigContainer",
      size: { width: "150px", height: "250px", backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-92",
  },
  {
    id: "93",
    type: "black-container",
    data: {
      label: "361RM1TZ2",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-93",
  },
  {
    id: "94",
    type: "black-container",
    data: {
      label: "361RM1PZ3",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mmWC",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-94",
  },
  {
    id: "95",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-95",
  },
  {
    id: "96",
    type: "text-container",
    data: { label: "361SR1", useClass: "yellowTxt", unit: "mmwC" },
    position: { x: 0, y: 0 },
    className: "id-96",
  },

  {
    id: "97",
    type: "black-container",
    data: {
      label: "RM1_TOT_FEED",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "TPH",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-97",
  },
  {
    id: "98",
    type: "black-container",
    data: {
      label: "361RM1PZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "MB",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-98",
  },
  {
    id: "99",
    type: "black-container",
    data: {
      label: "361HY1_ZZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "MM",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-99",
  },
  {
    id: "100",
    type: "black-container",
    data: {
      label: "361RM1AZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mm/s",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-100",
  },
  {
    id: "101",
    type: "box-container",
    data: {
      label: "GRIND PRESS",
      useClass: "blackTxt p-1",
      useStyle: { padding: "0px" },
      Children: [
        {
          label: "361HY1_MAN",
          useClass: "greenTxt  mw-60 lineheight14",
          unit: "",
          unitColor: "unitColor",
        },
        {
          label: "361HY1AI1",
          useClass: "greenTxt  mw-60 lineheight14 ",

          unit: "B",
          unitColor: "unitColor",
        },
      ],
    },
    position: { x: 0, y: 0 },
    className: "id-101",
  },
  {
    id: "102",
    type: "vertical-line",
    data: { label: "", useClass: "pipeVr pipeMiddleVr VrRotate" },
    position: { x: 0, y: 0 },
    className: "id-102",
  },
  {
    id: "103",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-103",
  },
  // {
  //   id: "104",
  //   type: "squrebox",
  //   data: { label: null, useClass: "" },
  //   position: { x: 0, y: 0 },
  //   className: "id-104 greenSqure",
  // },
  // {
  //   id: "105",
  //   type: "squrebox",
  //   data: { label: null, useClass: "" },
  //   position: { x: 0, y: 0 },
  //   className: "id-105 greenSqure",
  // },
  // {
  //   id: "106",
  //   type: "squrebox",
  //   data: { label: null, useClass: "" },
  //   position: { x: 0, y: 0 },
  //   className: "id-106 greenSqure",
  // },
  {
    id: "107",
    type: "black-container",
    data: {
      label: "361ROL1-ZZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mm",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-107",
  },
  {
    id: "108",
    type: "black-container",
    data: {
      label: "361ROL2-ZZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mm",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-108",
  },
  {
    id: "109",
    type: "black-container",
    data: {
      label: "361ROL3-ZZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mm",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-109",
  },
  {
    id: "110",
    type: "c-grn-box-1",
    data: {
      label: "361HY1CYL1-PZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mm",
    },
    position: { x: 0, y: 0 },
    className: "id-110",
  },
  {
    id: "111",
    type: "c-grn-box-2",
    data: {
      label: "361GB1TZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mm",
    },
    position: { x: 0, y: 0 },
    className: "id-111",
  },
  {
    id: "112",
    type: "down-arrow",
    data: {
      label: null,
      useStyle: { height: "77px" },
    },
    position: { x: 0, y: 0 },
    className: "id-112",
  },
  {
    id: "113",
    type: "image-data",
    data: {
      label: null,
      useClass: "triangle-with-squares",
      size: { width: "53px", height: "60px", backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-113",
  },
  {
    id: "114",
    type: "image-data",
    data: {
      label: null,
      useClass: "triangle-with-squares",
      size: { width: "53px", height: "60px", backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-114",
  },
  {
    id: "115",
    type: "image-data",
    data: {
      label: null,
      useClass: "triangle-with-squares",
      size: { width: "53px", height: "60px", backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-115",
  },
  {
    id: "116",
    type: "image-data",
    data: {
      label: null,
      useClass: "triangle-with-squares",
      size: { width: "53px", height: "60px", backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-116",
  },
  {
    id: "117",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-117",
  },
  {
    id: "118",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-118",
  },
  {
    id: "119",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-119",
  },
  {
    id: "120",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-120",
  },
  {
    id: "121",
    type: "black-container",
    data: {
      label: "361RM1-FZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mmWC",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-121",
  },
  {
    id: "122",
    type: "down-arrow",
    data: {
      label: null,
      useStyle: { height: "20px" },
    },
    position: { x: 0, y: 0 },
    className: "id-122",
  },
  {
    id: "123",
    type: "down-arrow",
    data: {
      label: null,
      useStyle: { height: "20px" },
    },
    position: { x: 0, y: 0 },
    className: "id-123",
  },
  {
    id: "124",
    type: "down-arrow",
    data: {
      label: null,
      useStyle: { height: "20px" },
    },
    position: { x: 0, y: 0 },
    className: "id-124",
  },
  {
    id: "125",
    type: "down-arrow",
    data: {
      label: null,
      useStyle: { height: "20px" },
    },
    position: { x: 0, y: 0 },
    className: "id-125",
  },
  {
    id: "126",
    type: "vertical-line",
    data: { label: "", useClass: "pipeVr pipeMiddleVr small-vr" },
    position: { x: 0, y: 0 },
    className: "id-126",
  },
  {
    id: "127",
    type: "horizontal-line",
    data: { label: "", useClass: "pipeHr pipeMiddleHr width-557" },
    position: { x: 0, y: 0 },
    className: "id-127",
  },
  {
    id: "128",
    type: "image-data",
    data: {
      label: null,
      useClass: "connector-icon",
      size: { backgroundSize: "cover" },
      subImage: "greenDot",
    },
    position: { x: 0, y: 0 },
    className: "id-128",
  },
  {
    id: "129",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-129",
  },
  {
    id: "130",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-130",
  },
  {
    id: "131",
    type: "box-container",
    data: {
      label: "361LD3",
      useClass: "yellowTxt p-1 mw-60",
      Children: [
        {
          label: "361LD3_PID:MV",
          useClass: "greenTxt",
          unit: "",
          unitColor: "unitColor",
        },
        {
          label: "361LD3-ZZ1",
          useClass: "greenTxt",
          unit: "%",
          unitColor: "unitColor",
        },
      ],
    },
    position: { x: 0, y: 0 },
    className: "id-131",
  },
  {
    id: "132",
    type: "down-arrow",
    data: {
      label: null,
      useStyle: { height: "66px" },
    },
    position: { x: 0, y: 0 },
    className: "id-132",
  },
  //   {
  //     id: "133",
  //     type: "down-arrow-line",
  //     data: {
  //       label: null,
  //       useStyle: { height: "20px" },
  //     },
  //     position: { x: 0, y: 0 },
  //     className: "id-133",
  //   },
  {
    id: "134",
    type: "text-container",
    data: { label: "TO 391MD1/431MD1", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-134",
  },
  {
    id: "135",
    type: "box-container-middle-table",
    data: {
      label: "",
      useClass: "yellowTxt p-1 mw-60",
    },
    position: { x: 0, y: 0 },
    className: "id-135",
  },
  {
    id: "136",
    type: "image-data",
    data: {
      label: null,
      useClass: "blue-pipe" /* asset17 */,
      size: { backgroundSize: "cover" },
      //   subImage: "greenDot",
    },
    position: { x: 0, y: 0 },
    className: "id-136",
  },
  {
    id: "137",
    type: "text-container",
    data: { label: "361FN2S", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-137",
  },
  {
    id: "138",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-138",
  },
  {
    id: "139",
    type: "text-container",
    data: { label: "361FN2", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-139",
  },
  {
    id: "140",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-140",
  },
  {
    id: "141",
    type: "black-container",
    data: {
      label: "361FN2PZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mmWG",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-141",
  },
  {
    id: "142",
    type: "horizontal-line",
    data: { label: "", useClass: "pipeHr pipeMiddleHr width-500" },
    position: { x: 0, y: 0 },
    className: "id-142",
  },
  {
    id: "143",
    type: "black-container",
    data: {
      label: "361RM1TZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-143",
  },
  {
    id: "144",
    type: "black-container",
    data: {
      label: "361RM1TZ1A",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-144",
  },
  {
    id: "145",
    type: "image-data",
    data: {
      label: null,
      useClass: "connector-container",
      size: { backgroundSize: "cover" },
      subImage: "greenDot",
    },
    position: { x: 0, y: 0 },
    className: "id-145",
  },
  {
    id: "146",
    type: "black-container",
    data: {
      label: "361RM1AZ2",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mm/s",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-146",
  },
  {
    id: "147",
    type: "text-container",
    data: { label: "361MD1", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-147",
  },
  {
    id: "148",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-148",
  },
  {
    id: "149",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-149",
  },
  {
    id: "150",
    type: "black-container",
    data: {
      label: "361MD1JZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "KW",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-150",
  },
  {
    id: "151",
    type: "black-container",
    data: {
      label: "361MD1IZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "A",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-151",
  },
  {
    id: "152",
    type: "black-container",
    data: {
      label: "RM1_POWER",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "KW/TPH",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-152",
  },
  {
    id: "153",
    type: "box-container-table-with-label",
    data: {
      label: "361MD1 Temperature",
      useClass: "yellowTxt p-1 mw-60",
      Children: [
        {
          label: "Winding",
          useClass: "yellowTxt",
          dataLabel: [
            {
              label: "3611X1TZ1",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "3611X1TZ2",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "3611X1TZ3",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
        {
          label: " ",
          dataLabel: [
            {
              label: "3611X1TZ4",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "3611X1TZ5",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "3611X1TZ6",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
        {
          label: "BRNG",
          dataLabel: [
            {
              label: "3611X1TZ7",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "3611X1TZ8",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },

        {
          label: "Stator",
          dataLabel: [
            {
              label: "3611X1TZ9",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "3611X1TZA",
              unitColor: "unitColor",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
            },
            {
              label: "3611X1TZB",
              unitColor: "unitColor",
              unit: "C",
              useClass: "greenTxt mw-60 lineheight14",
            },
          ],
        },
      ],
    },
    position: { x: 0, y: 0 },
    className: "id-153",
  },
  {
    id: "154",
    type: "vertical-line",
    data: { label: "", useClass: "pipeVr pipeMiddleVr" },
    position: { x: 0, y: 0 },
    className: "id-154",
  },
  {
    id: "155",
    type: "vertical-line",
    data: { label: "", useClass: "pipeVr pipeMiddleVr height-50" },
    position: { x: 0, y: 0 },
    className: "id-155",
  },
  {
    id: "156",
    type: "text-container",
    data: { label: "361TV2", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-156",
  },
  {
    id: "157",
    type: "black-container",
    data: {
      label: "361TV2_MAN:MV",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-157",
  },
  {
    id: "158",
    type: "black-container",
    data: {
      label: "361TV2-ZZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "%",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-158",
  },
  {
    id: "159",
    type: "text-container",
    data: { label: "FRESH AIR", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-159",
  },
  {
    id: "160",
    type: "text-container",
    data: { label: "361FN4", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-160",
  },
  {
    id: "161",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-161",
  },
  {
    id: "162",
    type: "text-container",
    data: { label: "361LD6", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-162",
  },
  {
    id: "163",
    type: "text-container",
    data: { label: "361LD4", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-163",
  },
  {
    id: "164",
    type: "black-container",
    data: {
      label: "361LD4_PID:MV",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-164",
  },
  {
    id: "165",
    type: "black-container",
    data: {
      label: "E311V2JZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "%",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-165",
  },
  {
    id: "166",
    type: "black-container",
    data: {
      label: "361LD6ZZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "%",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-166",
  },
  {
    id: "167",
    type: "vertical-line",
    data: { label: "", useClass: "pipeVr pipeMiddleVr height-120" },
    position: { x: 0, y: 0 },
    className: "id-167",
  },
  {
    id: "168",
    type: "vertical-line",
    data: { label: "", useClass: "pipeVr pipeMiddleVr height-80" },
    position: { x: 0, y: 0 },
    className: "id-168",
  },
  {
    id: "169",
    type: "text-container",
    data: { label: "Fresh Air", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-169",
  },
  {
    id: "170",
    type: "black-container",
    data: {
      label: "K1_361TV4ZZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "%",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-170",
  },
  {
    id: "171",
    type: "text-container",
    data: { label: "361TV4", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-171",
  },
  {
    id: "172",
    type: "black-container",
    data: {
      label: "K1_361TV3ZZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "%",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-172",
  },
  {
    id: "173",
    type: "text-container",
    data: { label: "361TV3", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-173",
  },
  {
    id: "174",

    type: "image-data",
    data: {
      label: null,
      useClass: "bagHouse",
      size: { backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-174",
  },
  {
    id: "175",
    type: "black-container",
    data: {
      label: "K1_421BH1TZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "°C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-175",
  },
  {
    id: "176",
    type: "black-container",
    data: {
      label: "K1_421BH1TZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "°C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-176",
  },
  {
    id: "177",
    type: "black-container",
    data: {
      label: "K1_421BH1PZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mm",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-177",
  },
  {
    id: "178",
    type: "black-container",
    data: {
      label: "K1_421BH1COMP_PZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "bar",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-178",
  },
  {
    id: "179",
    type: "black-container",
    data: {
      label: "K1_421BH1PZ3",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mm",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-179",
  },
  {
    id: "180",
    type: "graydot-with-text",
    data: {
      label: "M",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "",
    },
    position: { x: 0, y: 0 },
    className: "id-180",
  },
  {
    id: "181",
    type: "squrebox",
    data: { label: null, useClass: "" },
    position: { x: 0, y: 0 },
    className: "id-181 greenSqure",
  },
  {
    id: "182",
    type: "text-container",
    data: { label: "BAGHOUSE", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-182",
  },
  {
    id: "183",
    type: "black-container",
    data: {
      label: "K1_421BH1_TZ2",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "°C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-183",
  },
  {
    id: "184",
    type: "black-container",
    data: {
      label: "K1_421BH1PZ2",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mm",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-184",
  },
  {
    id: "185",
    type: "box-container-table-with-label",
    data: {
      label: "421FN2",
      useClass: "yellowTxt p-1 mw-60",
      Children: [
        {
          label: "",
          dataLabel: [
            {
              label: "K1_421FN2_AO",
              unit: "%",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },

            {
              label: "K1_421FN2_IZ1",
              unit: "A",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
        {
          label: "",
          dataLabel: [
            {
              label: "K1_421FN2_SZ1",
              unit: "RPM",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },

            {
              label: "K1_421FN2TZ1",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
        {
          label: "",
          dataLabel: [
            {
              label: "421FN2AZ1",
              unit: "mm/Sec",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },

            {
              label: "K1_421FN2TZ2",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },

        {
          label: "",
          dataLabel: [
            {
              label: "421FN2AZ2",
              unit: "MM/Sec",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
      ],
    },
    position: { x: 0, y: 0 },
    className: "id-185",
  },
  {
    id: "186",
    type: "black-container",
    data: {
      label: "391CV1IZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "A",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-186",
  },
  {
    id: "187",

    type: "h-pipe-circle",
    data: { label: "391CV1", useClass: "blackTxt p-1" },
    position: { x: 0, y: 0 },

    className: "id-187",
  },
  {
    id: "188",
    type: "black-container",
    data: {
      label: "391CV2IZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "A",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-188",
  },
  {
    id: "189",

    type: "h-pipe-circle",
    data: {
      label: "391CV2",
      useClass: "blackTxt p-1",
      useStyle: { width: "110px" },
    },
    position: { x: 0, y: 0 },

    className: "id-189",
  },
  {
    id: "190",
    type: "black-container",
    data: {
      label: "391CV3IZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "A",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-190",
  },
  {
    id: "191",

    type: "h-pipe-circle",
    data: {
      label: "391CV3",
      useClass: "blackTxt p-1",
      useStyle: { width: "160px" },
    },
    position: { x: 0, y: 0 },

    className: "id-191",
  },
  {
    id: "192",

    type: "h-pipe-circle",
    data: { label: "391CV5", useClass: "blackTxt p-1" },
    position: { x: 0, y: 0 },

    className: "id-192",
  },
  {
    id: "193",

    type: "text-container",
    data: { label: "From PH Fan", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-193",
  },

  {
    id: "194",

    type: "h-pipe-circle",
    data: {
      label: "391CV4",
      useClass: "blackTxt p-1",
      useStyle: { width: "265px" },
    },
    position: { x: 0, y: 0 },

    className: "id-194",
  },
  {
    id: "195",
    type: "horizontal-line",
    data: { label: "", useClass: "pipeYellow pipeMiddleYellow" },
    position: { x: 0, y: 0 },
    className: "id-195",
  },
  {
    id: "196",
    type: "vertical-line",
    data: {
      label: "",
      useClass: "pipeVrYellow pipeMiddleVrYellow",
      useStyle: { height: "170px" },
    },
    position: { x: 0, y: 0 },
    className: "id-196",
  },
  {
    id: "197",
    type: "vertical-line",
    data: {
      label: "",
      useClass: "pipeVrYellow pipeMiddleVrYellow",
      useStyle: { height: "55px" },
    },
    position: { x: 0, y: 0 },
    className: "id-197",
  },
  {
    id: "198",

    type: "text-container",
    data: { label: "421FN2", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-198",
  },
  {
    id: "199",

    type: "text-container",
    data: { label: "421SG1", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-199",
  },
  {
    id: "200",
    type: "image-data",
    data: {
      label: null,
      useClass: "mBox",
      size: { backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-200",
  },
  {
    id: "201",
    type: "horizontal-line",
    data: {
      label: "",
      useClass: "pipeYellow pipeMiddleYellow",
      useStyle: { width: "150px" },
    },
    position: { x: 0, y: 0 },
    className: "id-201",
  },

  {
    id: "203",
    type: "horizontal-line",
    data: {
      label: "",
      useClass: "pipeYellow pipeMiddleYellow",
      useStyle: { width: "55px" },
    },
    position: { x: 0, y: 0 },
    className: "id-203",
  },
  {
    id: "204",
    type: "image-data",
    data: {
      label: null,
      useClass: "mBox",
      size: { backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-204",
  },
  {
    id: "205",
    type: "horizontal-line",
    data: {
      label: "",
      useClass: "pipeYellow pipeMiddleYellow",
      useStyle: { width: "55px" },
    },
    position: { x: 0, y: 0 },
    className: "id-205",
  },
  {
    id: "206",
    type: "image-data",
    data: {
      label: null,
      useClass: "lightBox",
      size: { backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-206",
  },
  {
    id: "207",

    type: "text-container",
    data: { label: "421FN1", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-207",
  },
  {
    id: "209",
    type: "box-container-table-with-label",
    data: {
      label: "421LD1",
      useClass: "yellowTxt p-1 mw-60",
      Children: [
        {
          label: "",
          dataLabel: [
            {
              label: "K1_421LD1ZZ1",
              unit: "%",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },

        {
          label: "",
          dataLabel: [
            {
              label: "K1_421LD1_PID:MV.VALUE",
              unit: "mmwg",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },

        {
          label: "",
          dataLabel: [
            {
              label: "K1_421LD1_PID:IO.WSP.VALUE",
              unit: "mmwg",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
      ],
    },
    position: { x: 0, y: 0 },
    className: "id-209",
  },
  {
    id: "210",
    type: "box-container-table",
    data: {
      label: "",
      useClass: "yellowTxt p-1 mw-60",
      Children: [
        {
          label: "421FN1",
          dataLabel: [
            {
              label: "K1_421FN1_SP",
              unit: "%",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "K1_421FN1JZ1",
              unit: "KW",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "K1_421FN1IZ1",
              unit: "A",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
        {
          label: "BH FAN ",
          dataLabel: [
            {
              label: "K1_421FN1SZ1",
              unit: "%",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "K1_421FN1AZ1",
              unit: "mm/s",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "K1_421FN1AZ2",
              unit: "mm/s",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
        {
          label: "MOTOR",
          dataLabel: [
            {
              label: "K1_421FN1AZ2",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "K1_4211X1TZ3",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "K1_4211X1TZ2",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "K1_4211X1TZ4",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },

        {
          label: "TEMP",
          dataLabel: [
            {
              label: "K1_4211X1TZ5",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "K1_4211X1TZ6",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "K1_4211X1TZ8",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "K1_4211X1TZ7",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
        {
          label: "STATOR CORE TEMP   ",
          label2: "FAN BEARING TEMP",
          useColSpan: 5,

          dataLabel: [{}],
        },
        {
          label: "",
          dataLabel: [
            {
              label: "K1_4211X1TZ9",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "K1_4211X1TZB",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "K1_421FN1TZ1",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
            {
              label: "K1_421FN1TZ2",
              unit: "°C",
              useClass: "greenTxt mw-60 lineheight14",
              unitColor: "unitColor",
            },
          ],
        },
      ],
    },
    position: { x: 0, y: 0 },
    className: "id-210",
  },
  {
    id: "211",
    type: "text-container",
    data: { label: "361FN5", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-211",
  },
  {
    id: "212",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-212",
  },
  {
    id: "213",
    type: "text-container",
    data: { label: "361SD1", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-213",
  },
  {
    id: "214",
    type: "text-container",
    data: { label: "From PH Fan", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-214",
  },
  {
    id: "215",
    type: "text-container",
    data: { label: "To 431MD1", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-215",
  },
  {
    id: "216",
    type: "image-data",
    data: {
      label: null,
      useClass: "blendingSilo",
      size: { backgroundSize: "cover" },
    },
    position: { x: 0, y: 0 },
    className: "id-216",
  },
  {
    id: "217",
    type: "blank-container",
    data: {
      label: "",
      useStyle: "h",
    },
    position: { x: 0, y: 0 },
    className: "id-217",
  },
  {
    id: "218",
    type: "blank-container",
    data: {
      label: "",
      useStyle: "h",
    },
    position: { x: 0, y: 0 },
    className: "id-218",
  },
  {
    id: "219",
    type: "blank-container",
    data: {
      label: "",
      useStyle: "h",
    },
    position: { x: 0, y: 0 },
    className: "id-219",
  },
  {
    id: "220",
    type: "blank-container",
    data: {
      label: "",
      useStyle: "h",
    },
    position: { x: 0, y: 0 },
    className: "id-220",
  },
  {
    id: "221",
    type: "blank-container",
    data: {
      label: "",
      useStyle: "h",
    },
    position: { x: 0, y: 0 },
    className: "id-221",
  },
  {
    id: "222",
    type: "blank-container",
    data: {
      label: "",
      useStyle: "h",
    },
    position: { x: 0, y: 0 },
    className: "id-222",
  },
  {
    id: "223",
    type: "blank-container",
    data: {
      label: "",
      useStyle: "h",
    },
    position: { x: 0, y: 0 },
    className: "id-223",
  },
  {
    id: "224",
    type: "blank-container",
    data: {
      label: "",
      useStyle: "h",
    },
    position: { x: 0, y: 0 },
    className: "id-224",
  },
  {
    id: "225",
    type: "text-container",
    data: { label: "391MD2", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-225",
  },
  {
    id: "226",
    type: "text-container",
    data: { label: "391MD1", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-226",
  },
  {
    id: "227",
    type: "black-container",
    data: {
      label: "391MD2IZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "A",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-227",
  },
  {
    id: "228",
    type: "black-container",
    data: {
      label: "391MD2TZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-228",
  },
  {
    id: "229",
    type: "black-container",
    data: {
      label: "391MD1IZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "A",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-229",
  },
  {
    id: "230",
    type: "black-container",
    data: {
      label: "391MD1TZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-230",
  },
  {
    id: "231",
    type: "black-container",
    data: {
      label: "K1_431FM1_SP",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "TPH",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-231",
  },
  {
    id: "232",
    type: "black-container",
    data: {
      label: "K1_431FM1_FZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "TPH",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-232",
  },
  {
    id: "233",
    type: "black-container",
    data: {
      label: "K1_431FM1PZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mmW",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-233",
  },
  {
    id: "234",
    type: "black-container",
    data: {
      label: "K1_431DV1ZZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "%",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-234",
  },
  {
    id: "235",
    type: "black-container",
    data: {
      label: "K1_411FB1_WZ3",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "TON",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-235",
  },
  {
    id: "236",
    type: "black-container",
    data: {
      label: "K1_431DV2ZZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "%",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-236",
  },
  {
    id: "237",
    type: "black-container",
    data: {
      label: "K1_431FMPZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mmW",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-237",
  },
  {
    id: "238",
    type: "text-container",
    data: { label: "431MD2", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-238",
  },
  {
    id: "239",
    type: "black-container",
    data: {
      label: "K1_431MD2IZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "Amp",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-239",
  },
  {
    id: "240",
    type: "black-container",
    data: {
      label: "K1_431MD2_TZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "°C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-240",
  },

  {
    id: "241",
    type: "black-container",
    data: {
      label: "K1_431MD1IZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "Amp",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-241",
  },
  {
    id: "242",
    type: "black-container",
    data: {
      label: "K1_431MD1_TZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "°C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-242",
  },
  {
    id: "243",
    type: "text-container",
    data: { label: "431MD1", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-243",
  },
  {
    id: "244",
    type: "text-container",
    data: { label: "431MD4", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-244",
  },
  {
    id: "245",
    type: "black-container",
    data: {
      label: "C1_431MD4IZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "Amp",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-245",
  },
  {
    id: "246",
    type: "black-container",
    data: {
      label: "K1_431MD4_TZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "°C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-246",
  },
  {
    id: "247",
    type: "black-container",
    data: {
      label: "K1_431MD4JZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "KW",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-247",
  },

  {
    id: "248",
    type: "black-container",
    data: {
      label: "K1_431MD3_JZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "KW",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-248",
  },
  {
    id: "249",
    type: "black-container",
    data: {
      label: "K1_431MD3_TZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "°C",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-249",
  },
  {
    id: "250",
    type: "black-container",
    data: {
      label: "C1_431MD3IZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "Amp",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-250",
  },

  {
    id: "251",
    type: "black-container",
    data: {
      label: "K1_431DG1_AO1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "%",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-251",
  },
  {
    id: "252",
    type: "black-container",
    data: {
      label: "K1_431DG1ZZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "%",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-252",
  },
  {
    id: "253",
    type: "black-container",
    data: {
      label: "K1_431DG1_KILN",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "%",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-253",
  },
  {
    id: "254",
    type: "black-container",
    data: {
      label: "K1_431DG1ZZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "%",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-254",
  },
  {
    id: "255",
    type: "text-container",
    data: { label: "241BC2", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-255",
  },
  {
    id: "256",
    type: "black-container",
    data: {
      label: "311BC2_IZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "A",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-256",
  },
  {
    id: "257",
    type: "text-container",
    data: { label: "241BC3", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-257",
  },
  {
    id: "258",
    type: "vertical-line",
    data: {
      label: "",
      useClass: "yellowline-Hr",
      useStyle: { width: "3px", height: "18px" },
    },
    position: { x: 0, y: 0 },
    className: "id-258",
  },
  {
    id: "259",
    type: "vertical-line",
    data: {
      label: "",
      useClass: "yellowline-Hr",
      useStyle: { height: "3px", width: "200px" },
    },
    position: { x: 0, y: 0 },
    className: "id-259",
  },

  {
    id: "261",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-261",
  },

  {
    id: "263",
    type: "text-container",
    data: { label: "331MT1", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-263",
  },
  {
    id: "264",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "25px" } },
    position: { x: 0, y: 0 },
    className: "id-264",
  },
  {
    id: "265",
    type: "horizontal-line",
    data: {
      label: "",
      useClass: "yellowline-Hr",
      useStyle: { height: "3px", width: "180px" },
    },
    position: { x: 0, y: 0 },
    className: "id-265",
  },
  {
    id: "266",
    type: "box-container",
    data: {
      label: "",
      useClass: "blackTxt p-1 mw-60",
      useStyle: { height: "50px" },
      Children: [
        {
          label: "361WT1LZ1",
          useClass: "greenTxt",
          unit: "M",
          unitColor: "unitColor",
        },
      ],
    },
    position: { x: 0, y: 0 },
    className: "id-266",
  },
  {
    id: "267",
    type: "horizontal-line",
    data: {
      label: "",
      useClass: "yellowline-Hr",
      useStyle: { height: "3px", width: "45px" },
    },
    position: { x: 0, y: 0 },
    className: "id-267",
  },
  {
    id: "268",
    type: "text-container",
    data: { label: "361FD1", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-268",
  },
  {
    id: "269",
    type: "horizontal-line",
    data: {
      label: "",
      useClass: "yellowline-Hr",
      useStyle: { height: "3px", width: "172px" },
    },
    position: { x: 0, y: 0 },
    className: "id-269",
  },
  {
    id: "270",
    type: "black-container",
    data: {
      label: "K1_R2421FN1_S",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "MG/NM3",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-270",
  },
  {
    id: "271",
    type: "black-container",
    data: {
      label: "R2421FN1_DM1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "MG/NM3",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-271",
  },
  {
    id: "272",
    type: "black-container",
    data: {
      label: "391SB1-LZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "MTR",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-272",
  },
  {
    id: "273",
    type: "text-container",
    data: { label: "BLENDING SILO 391SB1", useClass: "" },
    position: { x: 0, y: 0 },
    className: "id-273",
  },
  {
    id: "274",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "45px" } },
    position: { x: 0, y: 0 },
    className: "id-274",
  },
  {
    id: "275",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "80px" } },
    position: { x: 0, y: 0 },
    className: "id-275",
  },
  {
    id: "276",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "80px" } },
    position: { x: 0, y: 0 },
    className: "id-276",
  },
  {
    id: "277",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "40px" } },
    position: { x: 0, y: 0 },
    className: "id-277",
  },
  {
    id: "278",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "40px" } },
    position: { x: 0, y: 0 },
    className: "id-278",
  },
  {
    id: "279",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "40px" } },
    position: { x: 0, y: 0 },
    className: "id-279",
  },
  {
    id: "280",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "35px" } },
    position: { x: 0, y: 0 },
    className: "id-280",
  },
  {
    id: "281",
    type: "vertical-line",
    data: {
      label: "",
      useClass: "yellowline-Hr",
      useStyle: { height: "3px", width: "114px" },
    },
    position: { x: 0, y: 0 },
    className: "id-281",
  },
  {
    id: "282",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "80px" } },
    position: { x: 0, y: 0 },
    className: "id-282",
  },
  {
    id: "283",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "40px" } },
    position: { x: 0, y: 0 },
    className: "id-283",
  },
  {
    id: "284",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "40px" } },
    position: { x: 0, y: 0 },
    className: "id-284",
  },
  {
    id: "285",
    type: "text-container",
    data: { label: "Feed Bin", useClass: "blackTxt" },
    position: { x: 0, y: 0 },
    className: "id-285",
  },
  {
    id: "286",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "85px" } },
    position: { x: 0, y: 0 },
    className: "id-286",
  },

  {
    id: "287",
    type: "black-container",
    data: {
      label: "K1_431FM2PZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "mmWC",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-287",
  },
  {
    id: "288",
    type: "black-container",
    data: {
      label: "K1_431FM2_FZ1",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "TPH",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-288",
  },
  {
    id: "289",
    type: "black-container",
    data: {
      label: "K1_431FM2_SP",
      useClass: "greenTxt mw-60 lineheight14",
      unit: "TPH",
      unitColor: "unitColor",
    },
    position: { x: 0, y: 0 },
    className: "id-289",
  },
  {
    id: "290",
    type: "text-container",
    data: { label: "241BC4", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-290",
  },
  {
    id: "291",
    type: "squrebox",
    data: { label: null, useClass: "" },
    position: { x: 0, y: 0 },
    className: "id-291 greenSqure",
  },
  {
    id: "292",
    type: "squrebox",
    data: { label: null, useClass: "" },
    position: { x: 0, y: 0 },
    className: "id-292 greenSqure",
  },
  {
    id: "293",
    type: "squrebox",
    data: { label: null, useClass: "" },
    position: { x: 0, y: 0 },
    className: "id-293 greenSqure",
  },
  {
    id: "294",
    type: "squrebox",
    data: { label: null, useClass: "" },
    position: { x: 0, y: 0 },
    className: "id-294 greenSqure",
  },
  {
    id: "295",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-295",
  },
  {
    id: "296",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-296",
  },
  {
    id: "297",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-297",
  },
  {
    id: "298",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-298",
  },
  {
    id: "299",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-299",
  },
  {
    id: "300",
    type: "greendot",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-300",
  },
  {
    id: "301",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "15px" } },
    position: { x: 0, y: 0 },
    className: "id-301",
  },
  {
    id: "302",
    type: "down-arrow",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-302",
  },
  {
    id: "303",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "10px" } },
    position: { x: 0, y: 0 },
    className: "id-303",
  },
  {
    id: "304",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "10px" } },
    position: { x: 0, y: 0 },
    className: "id-304",
  },
  {
    id: "305",
    type: "down-arrow",
    data: { label: null },
    position: { x: 0, y: 0 },
    className: "id-305",
  },
  {
    id: "306",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "20px" } },
    position: { x: 0, y: 0 },
    className: "id-306",
  },
  {
    id: "307",
    type: "down-arrow",
    data: { label: null, useStyle: { height: "25px" } },
    position: { x: 0, y: 0 },
    className: "id-307",
  },
 
  {
    id: "308",
    type: "squrebox",
    data: { label: null, useClass: "" },
    position: { x: 0, y: 0 },
    className: "id-308 greenSqure",
  },
  {
    id: "309",
    type: "vertical-line",
    data: {
      label: "",
      useClass: "progress-bar",
    },
    position: { x: 0, y: 0 },
    className: "id-309 progress",
  },
  {
    id: "310",
    type: "squrebox",
    data: { label: null, useClass: "" },
    position: { x: 0, y: 0 },
    className: "id-310 red-sqr",
  },
  {
    id: "311",
    type: "squrebox",
    data: { label: null, useClass: "" },
    position: { x: 0, y: 0 },
    className: "id-311 blk-square",
  },
  {
    id: "312",
    type: "text-container",
    data: { label: "431DG1", useClass: "yellowTxt" },
    position: { x: 0, y: 0 },
    className: "id-312",
  },
  
];
